; Common state file

;---------------------------------------------------------------------------
; Stand
[Statedef 0]
type = S
physics = S
sprpriority = 2
velset=0,0
anim=0

[STate 0]
type=PosSet
trigger1=Time=0
y=0

[STate 0]
type=CtrlSet
trigger1=RoundState=2
trigger1=(Prevstateno!=[190,194])&&(Prevstateno!=[1930,1999])&&(Prevstateno!=[8190,8199])
trigger1=Enemy,Life!=0
trigger1=Time>=1&&(Var(10)=[1,2])
value=0

[STate 0]
type=CtrlSet
trigger1=prevstateno!=[190,194]
trigger1=prevstateno!=[1900,1999]
trigger1=prevstateno!=5900
trigger1=Enemy,Stateno=5150
trigger1=Time>=1&&Var(10)!=0
value=1

[STate 0,]
type=VarSet
trigger1=Var(17)!=0
var(17)=0

[State 0, 1];覚醒時スプライト変更
type = ChangeAnim
triggerall=Var(13)=1
trigger1 = (Anim !=8000) && Anim != 5
trigger2 = Anim = 5 && AnimTime = 0
value = 8000

[State 0, 1]
type = ChangeAnim
;triggerall=PalNo=[1,6]
triggerall=Var(13)=0
trigger1 = (Anim != [0,2]) && Anim != 5
trigger2 = Anim = 5 && AnimTime = 0
value = 0

[State 0]
type = Changestate
;triggerall=PalNo=[1,6]
triggerall=Var(13)=0
trigger1 = (Anim =[1,2]) && AnimTime = 0
trigger2 = Anim=5
value = 1

[State 0, 2]
type = VelSet
trigger1 = Time = 0
y = 0

[STate 0]
type=Changeanim
;triggerall=PalNo=[1,6]
triggerall=Var(13)=0
trigger1=Anim=0&&Time=155&&Random<=777
value=1

[STate 0]
type=Changeanim
;triggerall=PalNo=[1,6]
triggerall=Var(13)=0
trigger1=Anim=0&&Time=155
value=2

[State 0,5]
type=DestroySelf
trigger1=Ishelper

[State 0]
type = Changestate
triggerall=var(10)!=0
triggerall=RoundState=2
triggerall=(Prevstateno!=[190,194])&&(Prevstateno!=[1930,1999])&&(Prevstateno!=[8190,8199])
triggerall = ctrl=0
trigger1 = time>=100
value = 6000

; Standかませ
[Statedef 1]
type = S
physics = S
sprpriority = 2
velset=0,0
[STate 1]
type=Changestate
trigger1=Anim!=5
trigger1=1
value=0
[STate 1]
type=Changestate
trigger1=Anim=5
trigger1=animtime=0
value=0

;---------------------------------------------------------------------------
; Stand to Crouch
[Statedef 10]
type    = C
physics = C
anim = 10
velset=0,0
sprpriority = 2            

[State 666];覚醒時スプライト変更
type = ChangeAnim
triggerall=Var(13)=1
trigger1 = time = 0
value = 8010
elem = 1

[State 10, 2]
type = ChangeState
trigger1 = AnimTime = 0
value = 11
;xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
;--------------- デッドエンドの覚醒から通常に戻り ---------------
[statedef 3]
type = S
movetype = I
physics = S
anim = 1
velset = 0
ctrl = 1

[state 3,1]
type = varset
trigger1 = time = 0
var(13) = 0

[state 3,2]
type = velset
trigger1 = time = 0
x = 0
y = 0

[state 3,3]
type = attackmulset
trigger1 = time = 0
value = 1
igonorehitpause = 1

[state 3,4]
type = defencemulset
trigger1 = time = 0
value = 1.5
igonorehitpause = 1

[state 3,5]
type = changestate
trigger1 = animtime = 0
value = 0
ctrl = 1
;---------------------------------------------------------------------------
; Crouching
[Statedef 11]
type    = C
physics = C
anim = 11
sprpriority = 2
velset=0,0

[State 666];覚醒時スプライト変更
type = ChangeAnim
triggerall=Var(13)=1
trigger1 = time=0
value = 8011
elem = 1

[State 11, 1] ;Change from turning animation
type = ChangeAnim
triggerall=Var(13)=0
trigger1 = Anim = 6 && AnimTime = 0
value = 11

;---------------------------------------------------------------------------
; Crouch to Stand
[Statedef 12]
type    = S
physics = S
anim = 12
velset=0,0
sprpriority = 2            

[State 10, 2]
type = ChangeAnim
triggerall=Var(13)=1
trigger1 = Time = 0
value = 8010

[State 12, 1]
type = ChangeState
trigger1 = AnimTime = 0
value = 0

;---------------------------------------------------------------------------
; Walk
[Statedef 20]
type    = S
physics = S
sprpriority = 2
movetype=I
velset=0,0

[STate 20]
type=Width
trigger1=1
value=-10,0

[State 20, 1]
type = VelSet
trigger1 = command = "holdfwd"
x = const(velocity.walk.fwd.x)

[State 20, 2]
type = VelSet
trigger1 = command = "holdback"
x = const(velocity.walk.back.x)

[STate 1]
type=VelAdd
triggerall=Var(13)=1
trigger1 = command = "holdfwd"
x=2

[STate 1]
type=VelAdd
triggerall=Var(13)=1
trigger1 = command = "holdback"
x=-2

[State 20, 3]
type = ChangeAnim
triggerall=Var(13)=1
triggerall = vel x > 0
trigger1 = Anim != 8020 && Anim != 5
trigger2 = Anim = 5 && AnimTime = 0
value = 8020

[State 20, 4]
type = ChangeAnim
triggerall=Var(13)=1
triggerall = vel x < 0
trigger1 = Anim != 8021 && Anim != 5
trigger2 = Anim = 5 && AnimTime = 0
value = 8021

[State 20, 3]
type = ChangeAnim
triggerall=Var(13)=0
triggerall = vel x > 0
trigger1 = Anim != 20 && Anim != 5
trigger2 = Anim = 5 && AnimTime = 0
value = 20

[State 20, 4]
type = ChangeAnim
triggerall=Var(13)=0
triggerall = vel x < 0
trigger1 = Anim != 21 && Anim != 5
trigger2 = Anim = 5 && AnimTime = 0
value = 21

;===========================================================================
; JUMPING SYSTEM
;===========================================================================
; Jump Start
[Statedef 40]
type    = S
physics = S
anim = IfElse((Var(13) > 0),50,40)
ctrl = 0
sprpriority = 1

[State 40, 1]
type = VarSet
trigger1 = time = 0
var(4) = 0

[State 40, 1];小ジャンプ
type = VarSet
trigger1 = command != "holdup"
var(4) = 1

[State 40, 1]
type = VarSet
trigger1 = Time = 0
sysvar(1) = 0

[State 40, 2]
type = VarSet
trigger1 = command = "holdfwd"
sysvar(1) = 1

[State 40, 3]
type = VarSet
trigger1 = command = "holdback"
sysvar(1) = -1

[State 40, 4]
type = VelSet
trigger1 = AnimTime = 0
trigger1 = Var(4) = 0
x = ifelse(sysvar(1)=0, const(velocity.jump.neu.x), ifelse(sysvar(1)=1, const(velocity.jump.fwd.x), const(velocity.jump.back.x)))
y = const(velocity.jump.y)

[State 40, 4];小ジャンプ
type = VelSet
trigger1 = AnimTime = 0
trigger1 = Var(4) = 1
x = ifelse(sysvar(1)=0, const(velocity.jump.neu.x), ifelse(sysvar(1)=1, const(velocity.jump.fwd.x), const(velocity.jump.back.x)))
y = -6

[State 40, 5]
type = VelSet
trigger1 = AnimTime = 0
trigger1 = prevstateno = 100 ;RUN_FWD
trigger1 = sysvar(1) = 1
x = const(velocity.runjump.fwd.x)

[State 191,]
type = PlaySnd
trigger1 = AnimTime = 0
trigger1 = prevstateno = 100 ;RUN_FWD
trigger1 = sysvar(1) = 1
trigger1 = Alive
value = S10000,1

[State 191,]
type = PlaySnd
triggerall = time = 0
;triggerall = Var(4) = 0
triggerall = Var(3) != 0
trigger1 = Alive
value = S0,1

[State 191,]
type = PlaySnd
triggerall = time = 0
triggerall = Var(4) = 0
triggerall = Var(3) = 0
trigger1 = Alive
value = S10000,0

[State 40, 6]
type = ChangeState
trigger1 = AnimTime = 0
value = 50
ctrl = 1

;---------------------------------------------------------------------------
; Jump Up
[Statedef 50]
type    = A
physics = A

[State 191,]
type = PlaySnd
triggerall = time = 0
triggerall = Var(4) = 1
triggerall = Var(3) = 0
trigger1 = Alive
value = S10000,0

[State 50, 1]
type = VarSet
trigger1 = Time = 0
sysvar(1) = 0

[State 50, 2]
type = ChangeAnim
triggerall = Var(13) = 0
trigger1 = Time = 0
value = ifelse((vel x)=0, 41, ifelse((vel x)>0, 42, 43))

[State 50, 2]
type = ChangeAnim
triggerall = Var(13) = 1
trigger1 = Time = 0
value = ifelse((vel x)=0, 51, ifelse((vel x)>0, 52, 53))

[State 50, 2];小ジャンプ
type = null;ChangeAnim
trigger1 = Time = 0
trigger1 = Var(4) = 1
value = 49

[State 50, 3]
type = ChangeAnim
trigger1 = Vel y > -2
trigger1 = SelfAnimExist(anim + 3)
persistent = 0
value = Anim + 3

;---------------------------------------------------------------------------
; Jump Land
[Statedef 52]
type    = S
physics = S
ctrl = 0
anim = IfElse((Var(13) > 0),57,47)
veladd = 0,0

[State 191,]
type = PlaySnd
trigger1 = time = 0
value = S10000,2

[State 52, 1]
type = VelSet
trigger1 = Time = 0
x = 0
y = 0

[State 52, 2]
type = PosSet
trigger1 = Time = 0
y = 0

[State 52, 3]
type = CtrlSet
trigger1 = Time = 3
value = 1

[State 52, 4]
type = ChangeState
trigger1 = AnimTime = 0
value = 0
ctrl = 1

;---------------------------------------------------------------------------
; RUN_FWD
[Statedef 100]
type    = S
physics = S
anim = 100
sprpriority = 2
velset=0,0
ctrl=0

[State 666];覚醒時スプライト変更
type = ChangeAnim
triggerall=Var(13)=1
trigger1 = time = 0
value = 8100
elem = 1

[State 100, 1]
type = VelSet
trigger1 = time>=1
x = const(velocity.run.fwd.x)

[STate 1]
type=VelAdd
triggerall=Var(13)=1
trigger1=time>=3
x=2

[State 100, 2] ;Prevent run from canceling into walk
type = AssertSpecial
trigger1 = 1
flag = NoWalk

[State 100, 3] ;Prevent from turning
type = AssertSpecial
trigger1 = 1
flag = NoAutoTurn

[State 100, 4]
type = ChangeState
triggerall=Time>=10
trigger1 = command != "holdfwd"
value = 101

[STate 0]
type=Changestate
trigger1=command = "holdup"
value=40

[State 100, 4]
type = ChangeState
triggerall=Time>=0
triggerall=Var(13)=0
trigger1 = command = "holdfwd"
trigger1 = command = "holddown"
value = 9120

[State 50,4]
type=PlaySnd
trigger1=Timemod=10,3
value=1,55
channel=6

[State 50,4]
type=StopSnd
trigger1=Time=1
channel=5

;---------------------------------------------------------------------------
; RUN_FWD（低姿勢）
[Statedef 9120]
type    = S
physics = S
anim = 9119
sprpriority = 2
velset=0,0
ctrl=0

[State 666];覚醒時スプライト変更
type = ChangeAnim
triggerall=Var(13)=1
trigger1 = time = 0
value = 8100
elem = 1

[State 100, 1]
type = VelSet
trigger1 = time>=1
x = const(velocity.run.fwd.x)

[STate 1]
type=VelAdd
triggerall=Var(13)=1
trigger1=time>=3
x=2

[State 100, 2] ;Prevent run from canceling into walk
type = AssertSpecial
trigger1 = 1
flag = NoWalk

[State 100, 3] ;Prevent from turning
type = AssertSpecial
trigger1 = 1
flag = NoAutoTurn

[State 100, 4]
type = ChangeState
triggerall=Time>=5
trigger1 = command != "holdfwd"
value = 101

[STate 0]
type=Changestate
trigger1=command = "holdup"
value=40

[State 100, 4]
type = ChangeState
triggerall=Time>=64
trigger1 = command = "holdfwd"
trigger1 = command = "holddown"
value = 9120

[State 100, 4]
type = ChangeState
triggerall=Time>=8
trigger1 = command = "holdfwd"
trigger1 = command != "holddown"
value = 100

[State 50,4]
type=PlaySnd
;trigger1=Timemod=11,0
trigger1=time=5
trigger2=time=16
trigger3=time=27
trigger4=time=38
trigger5=time=49
trigger6=time=60
value=6,3
channel=5

;---------------------------------------------------------------------------
;ストップ
[Statedef 101]
type    = S
physics = S
velset=0,0
ctrl = 0
anim = 0
sprpriority = 2

[State 666];覚醒時スプライト変更
type = ChangeAnim
triggerall=Var(13)=1
trigger1 = time = 0
value = 8000
elem = 1

[State 101,0]
type=stopSnd
trigger1=Time=0
channel=6

[STate 101,2]
type=Changestate
trigger1=time=3
value=0
ctrl=1

[State 50,4]
type=StopSnd
trigger1=Time=0
channel=5

;---------------------------------------------------------------------------
; RUN_BACK
[Statedef 105]
type    = A
movetype= A
physics = N
ctrl = 0
anim = 105
sprpriority = 2

[State 666];覚醒時スプライト変更
type = ChangeAnim
triggerall=Var(13)=1
trigger1 = time = 0
value = 10105
elem = 1

[State 9052, 1]
type = hitDef
trigger1 = AnimElem =1
trigger1 = PrevStateNo=9310
attr = S, NA
damage = 0
numhits = 0
animtype = hard
guardflag = 
hitflag = MAF
priority = 7, Hit
pausetime = 0,0
sparkno = -1
guard.sparkno=-1
sparkxy = -30, -75
hitsound = -1
guardsound = -1
ground.type = high
ground.slidetime =12
ground.hittime  = 12
ground.velocity = -4,-4
airguard.velocity = -4.4,-4
air.type = High
air.velocity = -5.4,-4
air.hittime = 55
;id = 1000023001
fall=1
fall.recover=0

[State 105, 1]
type = VelSet
trigger1 = Time = 0
x = -5.8
y = -3

[STate 1]
type=VelAdd
triggerall=Var(13)=1
trigger1 =time=0
x=-2

[STate 105]
type=gravity
trigger1=1

[State 106, 1]
type = null;Velmul
trigger1 = Time>=10&&Vel X<0
x=.1

[State 105, 3]
type = ChangeState
trigger1 = Vel Y > 0
trigger1 = Pos Y >= -1
value = 106

[State 105,4]
type=NotHitBy
trigger1=1
value=SAC

[State 105,0]
type=playsnd
trigger1=Time=1
value=1,20
channel=5
[State 105,0]
type=playsnd
trigger1=Time=1
value=1,20
channel=4

;[State 101,3]
;type=AfterImage
;trigger1=Time=0
;time=10
;trans=add1
;length=8
;---------------------------------------------------------------------------
; RUN_BACK2 (land)
[Statedef 106]
type    = S
physics = S
velset=0,0
ctrl = 0
anim = 47

[State 666];覚醒時スプライト変更
type = ChangeAnim
triggerall=Var(13)=1
trigger1 = time = 0
value = 57

[State 101,3]
type=AfterImagetime
trigger1=Time=0
time=0
[State 106, 2]
type = PosSet
trigger1 = Time = 0
y = 0
[State 106, 3]
type = MakeDust
trigger1 = Time = 2
pos = -5,-2
spacing = 1

[State 106, 4]
type = ChangeState
trigger1 = animtime=0
value = 0
ctrl = 1

;---------------------------------------------------------------------------
; RUN_UP
[Statedef 110]
type    = S
physics = N

[State 110, 0]
type = CtrlSet
trigger1 = Time = 0
value = 0

[State 110, 1]
type = ChangeAnim
trigger1 = Time = 0
value = 110

[State 110, 2]
type = HitBy
trigger1 = Time = 0
value = SCA, NT, ST, HT
time = 30

[State 110, 3]
type = VelSet
trigger1 = Time = 0
x = 0
z = -7

[State 110, 4]
type = VelMul
trigger1 = 1
z = 0.8

[State 110, 5]
type = VelSet
trigger1 = AnimTime = -8
z = 0

[State 110, 7]
type = CtrlSet
trigger1 = AnimTime = 0
value = 1

[State 110, 8]
type = ChangeState
trigger1 = AnimTime = 0
value = 0

;---------------------------------------------------------------------------
; RUN_DOWN
[Statedef 115]
type    = S
physics = N

[State 115, 0]
type = CtrlSet
trigger1 = Time = 0
value = 0

[State 115, 1]
type = ChangeAnim
trigger1 = Time = 0
value = 110

[State 115, 2]
type = HitBy
trigger1 = Time = 0
value = SCA, NT, ST, HT
time = 30

[State 115, 3]
type = VelSet
trigger1 = Time = 0
x = 0
z = 7

[State 115, 4]
type = VelMul
trigger1 = 1
z = 0.8

[State 115, 5]
type = VelSet
trigger1 = AnimTime = -8
z = 0

[State 115, 7]
type = CtrlSet
trigger1 = AnimTime = 0
value = 1

[State 115, 8]
type = ChangeState
trigger1 = AnimTime = 0
value = 0

;===========================================================================
; Guard System
;===========================================================================
; GUARD (start)
[Statedef 120]
type = U
physics = U

[State 120, Normal]
type = ChangeAnim
triggerall = var(13) = 0
trigger1 = Time = 0
value = 120 + (statetype = C) + (statetype = A)*2
[State 120, Riot]
type = ChangeAnim
triggerall = var(13) = 1
trigger1 = Time = 0
value = 125 + (statetype = C) + (statetype = A)*2

[State 120, 2]
type = StateTypeSet
trigger1 = Time = 0 && statetype = S
physics = S

[State 120, 3]
type = StateTypeSet
trigger1 = Time = 0 && statetype = C
physics = C

[State 120, 4]
type = StateTypeSet
trigger1 = Time = 0 && statetype = A
physics = A

[State 120, Hi to Lo]
type = StateTypeSet
trigger1 = var(55) = 0
trigger1 = statetype = S && command = "holddown"
trigger2 = var(55) > 0
trigger2 = statetype = S && enemynear,statetype = C
statetype = C
physics = C

[State 120, Lo to Hi]
type = StateTypeSet
trigger1 = var(55) = 0
trigger1 = statetype = C && command != "holddown"
trigger2 = var(55) > 0
trigger2 = statetype = C && enemynear,statetype = S
trigger2 = enemynear,time >= 16
trigger3 = var(55) > 0
trigger3 = statetype = C && enemynear,statetype = A
statetype = S
physics = S

[State 120, 5]
type = ChangeState
trigger1 = AnimTime = 0
value = 130 + (statetype = C) + (statetype = A)*2

[State 120, Stop Guarding]
type = ChangeState
trigger1 = var(55) = 0
trigger1 = command != "holdback"
trigger2 = !inguarddist
trigger3 = var(55)
trigger3 = enemynear,hitdefattr = SCA,AT
value = 140

;---------------------------------------------------------------------------
; Stand guard (guarding)
[Statedef 130]
type    = S
physics = S

[State 130, 1]
type = ChangeAnim
trigger1 = Anim != 130 && Anim != 135
value = IfElse((Var(13) > 0),135,130)

[State 130, Hi to Lo]
type = ChangeState
trigger1 = var(55) = 0
trigger1 = command = "holddown"
trigger2 = var(55) > 0
trigger2 = enemynear,statetype = C
value = 131

[State 130, Stop Guarding]
type = ChangeState
trigger1 = var(55) = 0
trigger1 = command != "holdback"
trigger2 = !inguarddist
trigger3 = var(55)
trigger3 = enemynear,hitdefattr = SCA,AT
value = 140

;---------------------------------------------------------------------------
; Crouch guard (guarding)
[Statedef 131]
type    = C
physics = C

[State 131, 1]
type = ChangeAnim
trigger1 = Anim != 131 && Anim != 136
value = IfElse((Var(13) > 0),136,131)

[State 131, Lo to Hi]
type = ChangeState
trigger1 = var(55) = 0
trigger1 = command != "holddown"
trigger2 = var(55) > 0
trigger2 = enemynear,statetype = S
trigger2 = enemynear,time >= 16
trigger3 = var(55) > 0
trigger3 = enemynear,statetype = A
value = 130

[State 131, Stop Guarding]
type = ChangeState
trigger1 = var(55) = 0
trigger1 = command != "holdback"
trigger2 = !inguarddist
trigger3 = var(55)
trigger3 = enemynear,hitdefattr = SCA,AT
value = 140

;---------------------------------------------------------------------------
; Air guard (guarding)
[Statedef 132]
type    = A
physics = N

[State 132, 1]
type = ChangeAnim
trigger1 = Anim != 132 && Anim != 137
value = IfElse((Var(13) > 0),137,132)

[State 132, 2]
type = VelAdd
trigger1 = 1
y = Const(movement.yaccel)

[State 132, 3]
type = VarSet
trigger1 = 1
sysvar(0) = (pos y >= 0) && (vel y > 0)

[State 132, 4]
type = VelSet
trigger1 = sysvar(0)
y = 0

[State 132, 5]
type = PosSet
trigger1 = sysvar(0)
y = 0

[State 132, 6]
type = ChangeState
triggerall = sysvar(0)
triggerall = inguarddist
trigger1 = var(55) = 0
trigger1 = command = "holdback"
trigger2 = var(55) > 0
value = 130

[State 132, 7]
type = ChangeState
trigger1 = sysvar(0)
value = 52

[State 132, Stop Guarding]
type = ChangeState
trigger1 = var(55) = 0
trigger1 = command != "holdback"
trigger2 = !inguarddist
value = 140

;---------------------------------------------------------------------------
; Guard (end)
[Statedef 140]
type = U    ;Leave state type unchanged
physics = U ;Leave physics unchanged
ctrl = 1

[State 140, Normal]
type = ChangeAnim
triggerall = var(13) = 0
trigger1 = Time = 0
value = 140 + (statetype = C) + (statetype = A)*2
[State 140, Riot]
type = ChangeAnim
triggerall = var(13) = 1
trigger1 = Time = 0
value = 145 + (statetype = C) + (statetype = A)*2

[State 140, 2]
type = StateTypeSet
trigger1 = Time = 0 && statetype = S
physics = S

[State 140, 3]
type = StateTypeSet
trigger1 = Time = 0 && statetype = C
physics = C

[State 140, 4]
type = StateTypeSet
trigger1 = Time = 0 && statetype = A
physics = A

[State 140, Hi to Lo]
type = StateTypeSet
trigger1 = var(55) = 0
trigger1 = statetype = S && command = "holddown"
trigger2 = var(55) > 0
trigger2 = statetype = S && enemynear,statetype = C
statetype = C
physics = C

[State 140, Lo to Hi]
type = StateTypeSet
trigger1 = var(55) = 0
trigger1 = statetype = C && command != "holddown"
trigger2 = var(55) > 0
trigger2 = statetype = C && enemynear,statetype = S
trigger2 = enemynear,time >= 16
trigger3 = var(55) > 0
trigger3 = statetype = C && enemynear,statetype = A
statetype = S
physics = S

;---------------------------------------------------------------------------
; Stand guard hit (shaking)
[Statedef 150]
type    = S
movetype= H
physics = N
velset = 0,0

[State 150, 1]
type = ChangeAnim
trigger1 = 1
value = IfElse((Var(13) > 0),155,150)

[State 150, 2]
type = ChangeState
trigger1 = HitShakeOver
value = 151 + 2*(command = "holddown")

[State 150, Hi to Lo]
type = StateTypeSet
trigger1 = var(55) = 0
trigger1 = statetype = S && command = "holddown"
trigger2 = var(55) > 0
trigger2 = statetype = S && enemynear,statetype = C
statetype = C
physics = C

[State 150, Lo to Hi]
type = StateTypeSet
trigger1 = var(55) = 0
trigger1 = statetype = C && command != "holddown"
trigger2 = var(55) > 0
trigger2 = statetype = C && enemynear,statetype = S
trigger2 = enemynear,time >= 16
trigger3 = var(55) > 0
trigger3 = statetype = C && enemynear,statetype = A
statetype = S
physics = S

[State 150, 3]
type = ForceFeedback
trigger1 = time = 0
waveform = square
time = 3

;---------------------------------------------------------------------------
; Stand guard hit (knocked back)
[Statedef 151]
type    = S
movetype= H
physics = S
anim = IfElse((Var(13) > 0),155,150)

[State 151, 1]
type = HitVelSet
trigger1 = Time = 0
x = 1

[State 151, 2]
type = VelSet
trigger1 = Time = GetHitVar(slidetime)
trigger2 = HitOver
x = 0

[State 151, 3]
type = CtrlSet
trigger1 = Time = GetHitVar(ctrltime)
value = 1

[State 151, Hi to Lo]
type = StateTypeSet
trigger1 = var(55) = 0
trigger1 = statetype = S && command = "holddown"
trigger2 = var(55) > 0
trigger2 = statetype = S && enemynear,statetype = C
statetype = C
physics = C

[State 151, Lo to Hi]
type = StateTypeSet
trigger1 = var(55) = 0
trigger1 = statetype = C && command != "holddown"
trigger2 = var(55) > 0
trigger2 = statetype = C && enemynear,statetype = S
trigger2 = enemynear,time >= 16
trigger3 = var(55) > 0
trigger3 = statetype = C && enemynear,statetype = A
statetype = S
physics = S

[State 151, 4]
type = ChangeState
trigger1 = HitOver
value = 130
ctrl = 1

;---------------------------------------------------------------------------
; Crouch guard hit (shaking)
[Statedef 152]
type    = C
movetype= H
physics = N
velset = 0,0

[State 152, 1]
type = ChangeAnim
trigger1 = 1
value = IfElse((Var(13) > 0),156,151)

[State 152, 3]
type = ChangeState
trigger1 = HitShakeOver
value = 151 + 2*(command = "holddown")

[State 152, Hi to Lo]
type = StateTypeSet
trigger1 = var(55) = 0
trigger1 = statetype = S && command = "holddown"
trigger2 = var(55) > 0
trigger2 = statetype = S && enemynear,statetype = C
statetype = C
physics = C

[State 152, Lo to Hi]
type = StateTypeSet
trigger1 = var(55) = 0
trigger1 = statetype = C && command != "holddown"
trigger2 = var(55) > 0
trigger2 = statetype = C && enemynear,statetype = S
trigger2 = enemynear,time >= 16
trigger3 = var(55) > 0
trigger3 = statetype = C && enemynear,statetype = A
statetype = S
physics = S

[State 152, 4]
type = ForceFeedback
trigger1 = time = 0
waveform = square
time = 4

;---------------------------------------------------------------------------
; Crouch guard hit (knocked back)
[Statedef 153]
type    = C
movetype= H
physics = C
anim = IfElse((Var(13) > 0),156,151)

[State 153, 1]
type = HitVelSet
trigger1 = Time = 0
x = 1

[State 153, 2]
type = VelSet
trigger1 = Time = GetHitVar(slidetime)
trigger2 = HitOver
x = 0

[State 153, 3]
type = CtrlSet
trigger1 = Time = GetHitVar(ctrltime)
value = 1

[State 153, Hi to Lo]
type = StateTypeSet
trigger1 = var(55) = 0
trigger1 = statetype = S && command = "holddown"
trigger2 = var(55) > 0
trigger2 = statetype = S && enemynear,statetype = C
statetype = C
physics = C

[State 153, Lo to Hi]
type = StateTypeSet
trigger1 = var(55) = 0
trigger1 = statetype = C && command != "holddown"
trigger2 = var(55) > 0
trigger2 = statetype = C && enemynear,statetype = S
trigger2 = enemynear,time >= 16
trigger3 = var(55) > 0
trigger3 = statetype = C && enemynear,statetype = A
statetype = S
physics = S

[State 153, 4]
type = ChangeState
trigger1 = HitOver
value = 131
ctrl = 1

;---------------------------------------------------------------------------
; Air guard hit (shaking)
[Statedef 154]
type    = A
movetype= H
physics = N
velset = 0,0

[State 154, 1]
type = ChangeAnim
trigger1 = 1
value = IfElse((Var(13) > 0),157,152)

[State 154, 2]
type = ChangeState
trigger1 = HitShakeOver
value = 155 ;AGUARDHIT2

[State 154, 3]
type = ForceFeedback
trigger1 = time = 0
waveform = square
time = 4

;---------------------------------------------------------------------------
; Air guard hit (knocked away)
[Statedef 155]
type    = A
movetype= H
physics = N
anim = IfElse((Var(13) > 0),157,152)

[State 155, 1]
type = HitVelSet
trigger1 = Time = 0
x = 1
y = 1

[State 155, 2]
type = VelAdd
trigger1 = 1
y = Const(movement.yaccel)

[State 155, 3]
type = CtrlSet
trigger1 = Time = GetHitVar(ctrltime)
value = 1

[State 155, 4]
type = VarSet
trigger1 = 1
sysvar(0) = (pos y >= 0) && (vel y > 0)

[State 155, 5]
type = VelSet
trigger1 = sysvar(0)
y = 0

[State 155, 6]
type = PosSet
trigger1 = sysvar(0)
y = 0

[State 155, 6]
type = ChangeState
trigger1 = sysvar(0)
trigger1 = command = "holdback"
trigger1 = inguarddist
value = 130

[State 155, 7]
type = ChangeState
trigger1 = sysvar(0)
value = 52

;---------------------------------------------------------------------------
; LOSE (Time over)
[Statedef 170]
type = S
ctrl = 0
anim = 170
velset = 0,0

[State 170, 1]
type = NotHitBy
trigger1 = 1
value = SCA
time = 1

;---------------------------------------------------------------------------
; DRAWGAME (Time over)
[Statedef 175]
type = S
ctrl = 0
velset = 0,0

[State 175, 1] ; If no anim, use go to lose state.
type = ChangeState
trigger1 = Time = 0
trigger1 = !SelfAnimExist(175)
value = 170

[State 175, 2]
type = ChangeAnim
trigger1 = Time = 0
value = 175

[State 175, 3]
type = NotHitBy
trigger1 = 1
value = SCA
time = 1

;---------------------------------------------------------------------------
; PREINTRO
[Statedef 190]
type = S
ctrl = 0
velset = 0,0

;[State 180, 1];デバッグ用
;type = ChangeState
;trigger1=Time=0
;value = 6370

[State 190, 1]
type = ChangeAnim
trigger1 = SelfAnimExist(190)
value = 190
;--------------------------------------
[State 190, 2] ;Go straight to intro.
type = ChangeState
trigger1=var(13) = 1
trigger1=Time=0
value = 8190
;--------------------------------------
[State 190, 2] ;Go straight to intro.
type = ChangeState
trigger1=Time=0
value = 191
;---------------------------------------------------------------------------
; K.O
[Statedef 8010]
type = S
physics = S
;anim = 6010
poweradd = 0
sprpriority = 8
velset = 0,0
ctrl = 0
facep2 = 1

[State 6010, PlaySound]
type = PlaySnd
trigger1 = time = 30
value = s5000,2

[State 6010, Explod]
type = Explod
trigger1 = time = 83
anim = f61
pos = 15,0
postype = p1
facing = 1
vfacing = 1
bindtime = 1
removetime = -2
sprpriority = -9

[State 6010, PlaySound]
type = PlaySnd
trigger1 = time = 83
value = f7,1

[State 6010, EnvShake]
type = EnvShake
trigger1 = time = 83
time = 10
freq = 110
ampl = -4

[State 6010, PalFX]
type = PalFX
trigger1 = time = 0
time = 0

[State 6010, anim]
type = Changeanim2
trigger1 = time = 0
value = 6010

[State 6010, air]
type = Changestate
trigger1 = pos Y != 0
value = 5000

[State 220, 3]
type = ChangeState
trigger1 = AnimTime = 0
value = 5150
;===========================================================================
; 5000 System
;===========================================================================
; HITG_SHAKE
[Statedef 5000]
type    = S
movetype= H
physics = N
velset = 0,0

[State 5000, 1]
type = ChangeAnim
trigger1 = time >= 0
trigger1 = NumHelper(6969) = 1
value = 25030

[State 5000, 1] ;Anim for HIT_LIGHT to HIT_HARD
type = ChangeAnim
triggerall = NumHelper(6969) = 0
trigger1 = Time = 0
trigger1 = GetHitVar(animtype) != [3,5]
value = ifelse((GetHitVar(groundtype) = 1),5000,5010) + GetHitVar(animtype)

[State 5000, 2] ;Anim for HIT_BACK
type = ChangeAnim
triggerall = NumHelper(6969) = 0
trigger1 = Time = 0
trigger1 = GetHitVar(animtype) = [3,5]
value = 5030

[State 5000, 3] ;Anim for HIT_UP/HIT_DIAGUP (only if it exists)
type = ChangeAnim
triggerall = NumHelper(6969) = 0
trigger1 = Time = 0
trigger1 = (GetHitVar(animtype) = [4,5]) && (SelfAnimExist(5047 + GetHitVar(animtype)))
value = 5047 + GetHitVar(animtype) ;5051 - 4 + type

[State 5000, 4] ;Freeze anim
type = ChangeAnim
trigger1 = Time > 0
value = anim

[State 5000, 5] ;State type gets set to aerial if getting hit up
type = StateTypeSet
trigger1 = Time = 0
trigger1 = GetHitVar(yvel) != 0 || GetHitVar(fall)
trigger2 = Pos Y != 0
statetype = a

[State 5000, 6]
type = ChangeState
trigger1 = HitShakeOver
trigger1 = GetHitVar(yvel) = 0 && !GetHitVar(fall)
value = 5001 ;HITG_SLIDE

[State 5000, 7]
type = ChangeState
trigger1 = HitShakeOver
value = 5030

[State 5000, FFB Light]
type = ForceFeedback
trigger1 = anim = 5000
trigger2 = anim = 5010
persistent = 0
time = 6
waveform = square

[State 5000, FFB Medium]
type = ForceFeedback
trigger1 = anim = 5001
trigger2 = anim = 5011
persistent = 0
time = 8
waveform = sinesquare
ampl = 110,-1,-.3

[State 5000, FFB Hard]
type = ForceFeedback
trigger1 = anim = 5012
trigger2 = anim = 5002
trigger3 = anim = 5030
persistent = 0
time = 15
waveform = sinesquare
ampl = 140

;---------------------------------------------------------------------------
; HITG_SLIDE
[Statedef 5001]
type    = S
movetype= H
physics = S
sprpriority = 1

[State 5001, 1]
type = HitVelSet
trigger1 = Time = 0
x = 1

[State 5001, 2]
type = ChangeAnim
trigger1 = AnimTime = 0
value = 5005 + GetHitVar(animtype) + (GetHitVar(groundtype)=2)*10

[State 5001, 3] ;Stop sliding back
type = VelMul
trigger1 = Time >= GetHitVar(slidetime)
x = .6

[State 5001, 4]
type = VelSet
trigger1 = HitOver
x = 0

[State 5001, 5]
type = DefenceMulSet
trigger1 = HitOver
value = 1

[State 5001, 6]
type = ChangeState
trigger1 = HitOver
value = 0
ctrl = 1

;---------------------------------------------------------------------------
; HITC_SHAKE
[Statedef 5010]
type    = C
movetype= H
physics = N
velset = 0,0
sprpriority = 1

[State 5010, 1] ;Anim for HIT_LIGHT to HIT_HARD
type = ChangeAnim
trigger1 = Time = 0
trigger1 = GetHitVar(animtype) != [3,5]
value = 5020 + GetHitVar(animtype)

[State 5010, 2] ;Anim for HIT_BACK
type = ChangeAnim
trigger1 = Time = 0
trigger1 = GetHitVar(animtype) = [3,5]
value = 5030

[State 5010, 3] ;Anim for HIT_UP/HIT_DIAGUP (only if it exists)
type = ChangeAnim
trigger1 = Time = 0
trigger1 = (GetHitVar(animtype) = [4,5]) && (SelfAnimExist(5047 + GetHitVar(animtype)))
value = 5047 + GetHitVar(animtype) ;5051 - 4 + type

[State 5010, 4] ;Freeze anim
type = ChangeAnim
trigger1 = Time > 0
value = anim

[State 5010, 5] ;State type gets set to aerial if getting hit up
type = StateTypeSet
triggerall = Time = 0
trigger1 = GetHitVar(yvel) != 0 || GetHitVar(fall)
trigger2 = Pos Y != 0
statetype = a

[State 5010, 6]
type = ChangeState
trigger1 = HitShakeOver
trigger1 = GetHitVar(yvel) = 0 && !GetHitVar(fall)
value = 5011 ;HITC_SLIDE

[State 5010, 7]
type = ChangeState
trigger1 = HitShakeOver
value = 5030

[State 5010, FFB Light]
type = ForceFeedback
trigger1 = anim = 5020
persistent = 0
time = 6
waveform = square

[State 5010, FFB Medium]
type = ForceFeedback
trigger1 = anim = 5021
persistent = 0
time = 8
waveform = sinesquare
ampl = 110,-1,-.3

[State 5010, FFB Hard]
type = ForceFeedback
trigger1 = anim = 5022
persistent = 0
time = 15
waveform = sinesquare
ampl = 140

;---------------------------------------------------------------------------
; HITC_SLIDE
[Statedef 5011]
type    = C
movetype= H
physics = C
sprpriority = 1

[State 5011, 1]
type = HitVelSet
trigger1 = Time = 0
x = 1

[State 5011, 2]
type = ChangeAnim
trigger1 = AnimTime = 0
value = 5025 + GetHitVar(animtype)

[State 5011, 3] ;Stop sliding back
type = VelMul
trigger1 = Time >= GetHitVar(slidetime)
x = .6

[State 5011, 4]
type = VelSet
trigger1 = HitOver
x = 0

[State 5011, 5]
type = DefenceMulSet
trigger1 = HitOver
value = 1

[State 5011, 6]
type = ChangeState
trigger1 = HitOver
value = 11
ctrl = 1


;---------------------------------------------------------------------------
; HITA_SHAKE
[Statedef 5020]
type    = A
movetype= H
physics = N
velset = 0,0

[State 5000, 1]
type = ChangeAnim
trigger1 = time >= 0
trigger1 = NumHelper(6969) = 1
value = 25030
ignorehitpause

[State 5020, 1] ;Anim for HIT_LIGHT to HIT_HARD
type = ChangeAnim
triggerall = NumHelper(6969) = 0
trigger1 = Time = 0
trigger1 = GetHitVar(animtype) != [3,5]
value = ifelse((GetHitVar(airtype) = 1),5000,5010) + GetHitVar(animtype)

[State 5020, 2] ;Anim for HIT_BACK
type = ChangeAnim
triggerall = NumHelper(6969) = 0
trigger1 = Time = 0
trigger1 = GetHitVar(animtype) = [3,5]
value = 5030

[State 5020, 3] ;Anim for HIT_UP/HIT_DIAGUP (only if it exists)
type = ChangeAnim
triggerall = NumHelper(6969) = 0
trigger1 = Time = 0
trigger1 = (GetHitVar(animtype) = [4,5]) && (SelfAnimExist(5047 + GetHitVar(animtype)))
value = 5047 + GetHitVar(animtype) ;5051 - 4 + type

[State 5020, 4] ;Freeze anim
type = ChangeAnim
trigger1 = Time > 0
value = anim

[State 5020, 5]
type = ChangeState
trigger1 = HitShakeOver
value = 5030

[State 5020, FFB Light]
type = ForceFeedback
trigger1 = anim = 5000
trigger2 = anim = 5010
persistent = 0
time = 6
waveform = square

[State 5020, FFB Medium]
type = ForceFeedback
trigger1 = anim = 5001
trigger2 = anim = 5011
persistent = 0
time = 8
waveform = sinesquare
ampl = 110,-1,-.3

[State 5020, FFB Hard]
type = ForceFeedback
trigger1 = anim = 5012
trigger2 = anim = 5002
trigger3 = anim = 5030
trigger4 = anim = [5051,5059]
persistent = 0
time = 15
waveform = sinesquare
ampl = 140

;---------------------------------------------------------------------------
; HITA_UP (initial going up)
[Statedef 5030]
type    = A
movetype= H
physics = N
ctrl = 0

; Normal
[State -2, 6]
type = PlaySnd
triggerall = Time = 1
triggerall = Var(50) = 0
trigger1 = alive = 0
value = 11,1
loop = 0

; Riot
[State -2, 6]
type = PlaySnd
triggerall = Time = 1
triggerall = Var(50) = 1
trigger1 = alive = 0
value = 0,36
loop = 0

[State 5000, 1]
type = ChangeAnim
trigger1 = time >= 0
trigger1 = NumHelper(6969) = 1
value = 25030

[State 5030, 1]
type = VelAdd;Gravity
trigger1 = 1
y = GetHitVar(yaccel)

[State 5030, 2]
type = HitVelSet
trigger1 = Time = 0
x = 1
y = 1

[State 5030, 3]
type = ChangeState
triggerall = !HitFall
trigger1 = HitOver
trigger2 = Vel Y > 0    ;Hit ground
trigger2 = Pos Y >= 10  ;.
value = 5040 ;HITA_RECOV

[State 5030, 4]
type = ChangeState
triggerall = HitFall
trigger1 = HitOver
trigger2 = Vel Y > 0    ;Hit ground
trigger2 = Pos Y >= 10  ;.
value = 5050 ;HITA_FALL

[State 5030, 5]
type = ChangeState
trigger1 = AnimTime = 0
value = 5035 ;HITA_UP (transition)

;---------------------------------------------------------------------------
; HITA_UP_T (transition)
[Statedef 5035]
type    = A
movetype= H
physics = N

[State 5000, 1]
type = ChangeAnim
trigger1 = time >= 0
trigger1 = NumHelper(6969) = 1
value = 25035

[State 5035, 1]
type = ChangeAnim
triggerall = NumHelper(6969) = 0
trigger1 = Time = 0
trigger1 = SelfAnimExist(5035)
trigger1 = Anim != [5051,5059] ;Not if in hit up anim
trigger1 = Anim != 5090 ;Not if hit off ground anim
value = 5035

[State 5035, 2]
type = VelAdd
trigger1 = 1
y = GetHitVar(yaccel)

[State 5035, 3]
type = ChangeState
triggerall = !HitFall
trigger1 = HitOver  ;Hit is over
trigger2 = AnimTime = 0 ;Animation over
trigger3 = Vel Y > 0    ;Hit ground
trigger3 = Pos Y >= 10  ;.
trigger4 = Time = 0     ;No transition anim
trigger4 = Anim != 5035 ;.
value = 5040 ;HITA_RECOV

[State 5035, 4]
type = ChangeState
triggerall = HitFall
trigger1 = HitOver  ;Hit is over
trigger2 = AnimTime = 0 ;Anim is over
trigger3 = Vel Y > 0    ;Hit ground
trigger3 = Pos Y >= 10  ;.
trigger4 = Time = 0     ;No transition anim
trigger4 = Anim != 5035 ;.
value = 5050 ;HITA_FALL

;---------------------------------------------------------------------------
; HITA_RECOV (recovering in air, not falling)
[Statedef 5040]
type    = A
movetype= H
physics = N

[State 5040, NotHitBy]
type = NotHitBy
trigger1 =ANIM  =5040
value =SCA

[State 5040, 1]
type = ChangeState
trigger1 = !Alive
value = 5050

[State 5040, 2]
type = ChangeAnim
trigger1 = AnimTime = 0
trigger1 = Anim != 5040
trigger2 = Time = 0
trigger2 = Anim != 5035
value = 5040

[State 5040, 3]
type = CtrlSet
trigger1 = HitOver
value = 0

[State 5040, 4]
type = StateTypeSet
trigger1 = HitOver
movetype = I

[State 5040, 5]
type = VelAdd
trigger1 = 1
y = GetHitVar(yaccel)

[State 5040, 6]
type = ChangeState
trigger1 = Vel Y > 0
trigger1 = Pos Y >= 0
value = 52

;---------------------------------------------------------------------------
; HITA_FALL (knocked up, falling)
[Statedef 5050]
type    = A
movetype= H
physics = N

[State 5000, 1]
type = ChangeAnim
trigger1 = time = 0
trigger1 = NumHelper(6969) = 1
value = 25050

[State 5050, 1] ;Change anim when done with transition
type = ChangeAnim
triggerall = NumHelper(6969) = 0
trigger1 = AnimTime = 0
trigger1 = Anim = 5035
trigger2 = Time = 0     ;If no transition anim
trigger2 = Anim != 5035
trigger2 = (Anim != [5051, 5059]) && (Anim != [5061, 5069])
trigger2 = Anim != 5090 ;Not if hit off ground anim
value = 5050

[State 5050, 2] ;Coming down anim
type = ChangeAnim
triggerall = NumHelper(6969) = 0
trigger1 = anim = [5050,5059]
trigger1 = Vel Y >= ifelse(anim = 5050, 1, -2)
trigger1 = SelfAnimExist(anim+10)
value = anim+10
persistent = 0

[State 5050, 3] ;Gravity
type = VelAdd
trigger1 = 1
y = GetHitVar(yaccel)

[State 5050, 4] ;Recover near ground
type = ChangeState
triggerall = Vel Y > 0
triggerall = Pos Y >= -30
triggerall = alive
triggerall = CanRecover
trigger1 = Command = "recovery"
value = 5200 ;HITFALL_RECOVER

;[State 5050, 5]; Recover in mid air
;type = ChangeState
;triggerall = Vel Y > -1
;triggerall = alive
;triggerall = CanRecover
;trigger1 = Command = "recovery"
;value = 5210 ;HITFALL_AIRRECOVER

[State 5050, 6]
type = ChangeState
trigger1 = Vel Y > 0
trigger1 = Pos Y >= ifelse((anim = [5051,5059]) || (anim = [5061,5069]), 0, 25)
value = 5100 ;HIT_BOUNCE

;---------------------------------------------------------------------------
; HIT_TRIP (shaking)
[Statedef 5070]
type    = A
movetype= H
physics = N
velset = 0,0
sprpriority = 1

[State 5070, 1]
type = ChangeAnim
trigger1 = 1
value = 5070

[State 5070, 2]
type = ChangeState
trigger1 = HitShakeOver
value = 5071

[State 1000, NotHitBy]
type = NotHitBy
trigger1 = 1
value = SCA

[State 5070, 3]
type = ForceFeedback
trigger1 = time = 0
time = 12
waveform = sinesquare
ampl = 140

;---------------------------------------------------------------------------
; HIT_TRIP2 (fall through air)
[Statedef 5071]
type    = A
movetype= H
physics = N
sprpriority = 1

[State 5071, 1]
type = HitVelSet
trigger1 = Time = 0
x = 1
y = 1

[State 5071, 2] ;Acceleration
type = VelAdd
trigger1 = 1
y = GetHitVar(yaccel)

[State 1000, NotHitBy]
type = NotHitBy
trigger1 = 1
value = SCA

[State 5071, 3] ;Hit ground
trigger1 = Vel Y > 0
trigger1 = Pos Y >= 15
type = ChangeState
value = 5100

;---------------------------------------------------------------------------
; HITL_SHAKE
[Statedef 5080]
type    = L
movetype= H
physics = N
velset = 0,0
sprpriority = 1

[State 5080, 1] ;Set default anim
type = VarSet
trigger1 = time = 0
sysvar(2) = ifelse (GetHitVar(yvel) = 0, 5080, 5090)

[State 5080, 2]
type = VarAdd
trigger1 = time = 0
trigger1 = (anim = [5081,5089]) || (anim = [5111,5119])
trigger1 = SelfAnimExist(sysvar(2) + (anim % 10))
sysvar(2) = anim % 10

[State 5080, 3] ;If 5090 doesn't exist, default to 5030
type = VarSet
trigger1 = time = 0
trigger1 = sysvar(2) = 5090
trigger1 = !SelfAnimExist(5090)
sysvar(2) = 5030

[State 5080, 3] ;Freeze
type = ChangeAnim
trigger1 = 1
value = sysvar(2)

[State 5080, 4]
type = ChangeState
trigger1 = HitShakeOver
trigger1 = GetHitVar(yvel) = 0
value = 5081 ;HITL_SLIDE

[State 5080, 5]
type = ChangeState
trigger1 = HitShakeOver
trigger1 = GetHitVar(yvel) != 0
value = 5030 ;HITA_UP

;---------------------------------------------------------------------------
; HITL_SLIDE
[Statedef 5081]
type    = L
movetype= H
physics = C
sprpriority = 1

[State 5081, 1]
type = HitVelSet
trigger1 = Time = 0
x = 1

[State 5081, 2]
type = VelSet
trigger1 = HitOver
x = 0

[State 5081, 3] ;Don't show hit ground frame
type = VarSet
trigger1 = Time = 0
sysvar(0) = 1

[State 5081, 4]
type = ChangeState
trigger1 = HitOver
value = 5110 ;HIT_LIEDOWN

;---------------------------------------------------------------------------
; HIT_BOUNCE (hit ground)
[Statedef 5100]
type    = L
movetype= H
physics = N

[State 5000, 1]
type = ChangeAnim
trigger1 = time = 0
trigger1 = NumHelper(6969) = 1
value = 25100

[State 5100, 1]
type = VelSet
trigger1 = Time = 0
trigger1 = GetHitVar(fall.yvel) = 0
trigger1 = vel x > 1
x = 1

[State 5100, EnvShake]
type = FallEnvShake
trigger1 = Time = 0

[State 5100, Var] ;Save fall velocity
type = VarSet
trigger1 = Time = 0
sysvar(1) = floor(vel y)

[State 5100, 2] ;Hit ground anim (normal)
type = ChangeAnim
triggerall = NumHelper(6969) = 0
;triggerall = var(22) = 0
triggerall = time = 0
trigger1 = (anim != [5051,5059]) && (anim != [5061,5069])
trigger2 = !SelfAnimExist(5100 + (anim % 10))
value = 5100

[State 5100, 3] ;Hit ground anim (for hit up)
type = ChangeAnim
triggerall = NumHelper(6969) = 0
;triggerall = var(22) = 0
trigger1 = time = 0
trigger1 = (anim = [5051,5059]) || (anim = [5061,5069])
trigger1 = SelfAnimExist(5100 + (anim % 10))
value = 5100 + (anim % 10)

[State 5100, 2] ;Hit ground anim (normal)
type = null;ChangeAnim
triggerall = NumHelper(6969) = 0
triggerall = var(22) != 0
triggerall = time = 0
trigger1 = (anim != [15051,15059]) && (anim != [15061,15069])
trigger2 = !SelfAnimExist(15100 + (anim % 10))
value = 15100

[State 5100, 3] ;Hit ground anim (for hit up)
type = null;ChangeAnim
triggerall = NumHelper(6969) = 0
triggerall = var(22) != 0
trigger1 = time = 0
trigger1 = (anim = [15051,15059]) || (anim = [15061,15069])
trigger1 = SelfAnimExist(15100 + (anim % 10))
value = 15100 + (anim % 10)

[State 5100, 1]
type = width
trigger1 = time = 0
edge = 10,10

[State 5100, 4]
type = PosSet
trigger1 = Time = 0
y = 0

[State 5100, 5]
type = VelSet
trigger1 = Time = 0
y = 0

[State 5100, 6] ;Reduce speed
type = VelMul
trigger1 = Time = 0
x = 0.75

[State 5100, 7]
type = ChangeState
trigger1 = Time = 0
trigger1 = GetHitVar(fall.yvel) = 0
value = 5110 ;HIT_LIEDOWN

[State 5100, 8]
type = GameMakeAnim
trigger1 = Time = 1
value = 60 + (sysvar(1) > 5)
pos = 0, 0
under = sysvar(0) <= 5

[State 5100, Explod]
type = Explod
trigger1 = Time = 0
trigger1 = (sysvar(1) > 14)
anim = f62
pos = 0,0
postype = p1
removetime = -2
pausemove = 1
sprpriority = 9

[State 5100, Explod]
type = Explod
trigger1 = Time = 0
trigger1 = (sysvar(1) > 14)
anim = f63
pos = 0,0
postype = p1
removetime = -2
pausemove = 1
sprpriority = -9

[State 5100, KOFM]
type = EnvShake
trigger1 = Time = 0
trigger1 = (sysvar(1) > 14)
time = 25
freq = 210
ampl = 10

[State 1000, LifeAdd]
type = LifeAdd
trigger1 = (sysvar(1) > 14)
trigger1 = Timemod = 3,0
value = 0
kill = 1

[State 5100, 11]
type = HitFallDamage
trigger1 = Time = 3

[State 5100, 12]
type = PlaySnd
trigger1 = Time = 1
value = F7, (sysvar(1) > 5) + (sysvar(1) > 14)

[State 5100, 11]
type = PosFreeze
trigger1 = 1

[State 5100, 12]
type = ChangeState
trigger1 = AnimTime = 0
trigger2 = anim = 25100 && time = 5
value = 5101

[State 5100, 13]
type = ForceFeedback
trigger1 = Time = 0
waveform = sinesquare
ampl = 128,-3,-.2,.005
time = 20

;---------------------------------------------------------------------------
; HIT_BOUNCE (bounce into air)
[Statedef 5101]
type    = L
movetype= H
physics = N

[State 5000, 1]
type = ChangeAnim
trigger1 = time = 0
trigger1 = NumHelper(6969) = 1
value = 25160

[State 5101, 1] ;Coming hit ground anim (normal)
type = ChangeAnim
triggerall = NumHelper(6969) = 0
;triggerall = var(22) = 0
triggerall = time = 0
trigger1 = anim != [5101,5109]
trigger2 = !SelfAnimExist(5160 + (anim % 10))
value = 5160

[State 5101, 2] ;Coming hit ground anim (for hit up)
type = ChangeAnim
triggerall = NumHelper(6969) = 0
;triggerall = var(22) = 0
triggerall = time = 0
trigger1 = anim = [5101,5109]
trigger1 = SelfAnimExist(5160 + (anim % 10))
value = 5160 + (anim % 10)

[State 5101, 1] ;Coming hit ground anim (normal)
type = null;ChangeAnim
triggerall = NumHelper(6969) = 0
triggerall = var(22) != 0
triggerall = time = 0
trigger1 = anim != [15101,15109]
trigger2 = !SelfAnimExist(15160 + (anim % 10))
value = 15160

[State 5101, 2] ;Coming hit ground anim (for hit up)
type = null;ChangeAnim
triggerall = NumHelper(6969) = 0
triggerall = var(22) != 0
triggerall = time = 0
trigger1 = anim = [15101,15109]
trigger1 = SelfAnimExist(15160 + (anim % 10))
value = 15160 + (anim % 10)

[State 5101, 3]
type = HitFallVel
trigger1 = Time = 0

[State 5101, 4]
type = PosSet
trigger1 = Time = 0
y = 20

[State 5101, 5] ;Acceleration
type = VelAdd
trigger1 = 1
y = .4

[State 5100 ,KOFM]
type = pause
trigger1 = (sysvar(1) > 14)
trigger1 = Timemod = 3,0
time = 3

[State 5101, 6] ;Hit ground
trigger1 = Vel Y > 0
trigger1 = Pos Y >= 12
type = ChangeState
value = 5110

;---------------------------------------------------------------------------
; HIT_LIEDOWN
[Statedef 5110]
type    = L
movetype= H
physics = N

[State 5110, 1]
type = width
trigger1 = time = 0
edge = 10,10

[State 5000, 1]
type = ChangeAnim
trigger1 = time = 0
trigger1 = NumHelper(6969) = 1
value = 25170

[State 5110, EnvShake]
type = FallEnvShake
trigger1 = Time = 0

[State 5110, 1] ;For hit up/up-diag type (from state 5081)
type = ChangeAnim
triggerall = NumHelper(6969) = 0
;triggerall = var(22) = 0
persistent = 0
trigger1 = SelfAnimExist(5110 + (anim % 10))
trigger1 = anim = [5081,5089]
value = 5110 + (anim % 10)

[State 5110, 2] ;Hit ground anim (normal)
type = ChangeAnim
triggerall = NumHelper(6969) = 0
;triggerall = var(22) = 0
triggerall = time = 0
triggerall = anim != [5110,5119] ;Not already changed anim
trigger1 = anim != [5161,5169]
trigger2 = !SelfAnimExist(5170 + (anim % 10))
value = 5170

[State 5110, 3] ;Hit ground anim (for hit up)
type = ChangeAnim
triggerall = NumHelper(6969) = 0
;triggerall = var(22) = 0
triggerall = time = 0
triggerall = anim != [5110,5119] ;Not already changed anim
trigger1 = anim = [5161,5169]
trigger1 = SelfAnimExist(5170 + (anim % 10))
value = 5170 + (anim % 10)

[State 5110, 1] ;For hit up/up-diag type (from state 5081)
type = null;ChangeAnim
persistent = 0
triggerall = NumHelper(6969) = 0
triggerall = var(22) != 0
trigger1 = SelfAnimExist(15110 + (anim % 10))
trigger1 = anim = [15081,15089]
value = 15110 + (anim % 10)

[State 5110, 2] ;Hit ground anim (normal)
type = null;ChangeAnim
triggerall = NumHelper(6969) = 0
triggerall = var(22) != 0
triggerall = time = 0
triggerall = anim != [15110,15119] ;Not already changed anim
trigger1 = anim != [15161,15169]
trigger2 = !SelfAnimExist(15170 + (anim % 10))
value = 15170

[State 5110, 3] ;Hit ground anim (for hit up)
type = null;ChangeAnim
triggerall = NumHelper(6969) = 0
triggerall = var(22) != 0
triggerall = time = 0
triggerall = anim != [15110,15119] ;Not already changed anim
trigger1 = anim = [15161,15169]
trigger1 = SelfAnimExist(15170 + (anim % 10))
value = 15170 + (anim % 10)

[State 5110, 4]
type = HitFallDamage
trigger1 = Time = 0

[State 5110, 5]
type = PosSet
trigger1 = Time = 0
y = 0

[State 5110, Var] ;Get fall velocity
type = VarSet
trigger1 = Time = 0
trigger1 = GetHitVar(fall.yvel) != 0
sysvar(1) = floor(vel y)

[State 5110, 6]
type = PlaySnd
trigger1 = Time = 0
trigger1 = !SysVar(0)
value = F7, (sysvar(1) > 5) + (sysvar(1) > 14)

[State 5110, 7]
type = GameMakeAnim
trigger1 = Time = 0
trigger1 = !SysVar(0)
value = 60 + (sysvar(1) > 5) + (sysvar(1) > 14)
pos = 0, 0
under = sysvar(1) <= 14

[State 5110, 8]
type = VelSet
trigger1 = Time = 0
y = 0

[State 5110, 1]
type = width
trigger1 = time = 0
edge = 10,10

[State 5110, 9] ;For hit up type
type = ChangeAnim
triggerall = NumHelper(6969) = 0
;triggerall = var(22) = 0
persistent = 0
triggerall = anim = [5171,5179]
triggerall = SelfAnimExist(5110 + (anim % 10))
trigger1 = AnimTime = 0
trigger2 = SysVar(0) ;SysVar(0) = 1 avoids hit ground anim
value = 5110 + (anim % 10)

[State 5110, 10] ;For normal
type = ChangeAnim
triggerall = NumHelper(6969) = 0
;triggerall = var(22) = 0
persistent = 0
triggerall = Anim != [5111,5119]
trigger1 = AnimTime = 0
trigger2 = SysVar(0) ;SysVar(0) = 1 avoids hit ground frame
value = 5110

[State 5110, 9] ;For hit up type
type = null;ChangeAnim
persistent = 0
triggerall = NumHelper(6969) = 0
triggerall = var(22) != 0
triggerall = anim = [15171,15179]
triggerall = SelfAnimExist(15110 + (anim % 10))
trigger1 = AnimTime = 0
trigger2 = SysVar(0) ;SysVar(0) = 1 avoids hit ground anim
value = 15110 + (anim % 10)

[State 5110, 10] ;For normal
type = null;ChangeAnim
persistent = 0
triggerall = NumHelper(6969) = 0
triggerall = var(22) != 0
triggerall = Anim != [15111,15119]
trigger1 = AnimTime = 0
trigger2 = SysVar(0) ;SysVar(0) = 1 avoids hit ground frame
value = 15110

[State 5110, 11] ;If just died
type = ChangeState
triggerall = !alive
;triggerall = var(22) = 0
trigger1 = AnimTime = 0
trigger2 = SysVar(0) ;SysVar(0) = 1 avoids hit ground frame
trigger3 = Anim = [5110,5119]
trigger4 = anim = 25170 && time = 5
value = 5150

[State 5110, 11] ;If just died
type = null;ChangeState
triggerall = var(22) != 0
triggerall = !alive
trigger1 = AnimTime = 0
trigger2 = SysVar(0) ;SysVar(0) = 1 avoids hit ground frame
trigger3 = Anim = [15110,15119]
value = 5150

[State 5110, 12]
type = VarSet
trigger1 = SysVar(0)
trigger1 = Time = 0
sysvar(0) = 0

[State 5110, 13] ;Friction
type = VelMul
trigger1 = 1
x = 0.85

[State 5110, 14]
type = ForceFeedback
trigger1 = alive
trigger1 = Time = 0
time = 8
ampl = 240
waveform = sine

[State 5110, 15]
type = ForceFeedback
trigger1 = !alive
trigger1 = Time = 0
ampl = 200, 7, -.467
time = 30
waveform = sine

;---------------------------------------------------------------------------
; HIT_LIEDOWN
[Statedef 5111]
type    = L
movetype= H
physics = N
ctrl    = 0

[State 5110, EnvShake]
type = FallEnvShake
trigger1 = Time = 0

[State 5110, 1] ;For hit up/up-diag type (from state 5081)
type = ChangeAnim
persistent = 0
trigger1 = SelfAnimExist(5110 + (anim % 10))
trigger1 = anim = [5081,5089]
value = 5110 + (anim % 10)

[State 5110, 1] ;For hit up/up-diag type (from state 5081)
type = ChangeAnim
persistent = 0
trigger1 = SelfAnimExist(5110 + (anim % 10))
trigger1 = anim = [5091,5099]
value = 5110 + (anim % 10)

[State 5110, 2] ;Hit ground anim (normal)
type = ChangeAnim
triggerall = time = 0
triggerall = anim != [5110,5119] ;Not already changed anim
trigger1 = anim != [5161,5169]
trigger2 = !SelfAnimExist(5170 + (anim % 10))
value = 5170

[State 5110, 3] ;Hit ground anim (for hit up)
type = ChangeAnim
triggerall = time = 0
triggerall = anim != [5110,5119] ;Not already changed anim
trigger1 = anim = [5161,5169]
trigger1 = SelfAnimExist(5170 + (anim % 10))
value = 5170 + (anim % 10)

[State 5110, 4]
type = HitFallDamage
trigger1 = Time = 0

[State 5110, 5]
type = PosSet
trigger1 = Time = 0
y = 0

[State 5110, Var] ;Get fall velocity
type = VarSet
trigger1 = Time = 0
trigger1 = GetHitVar(fall.yvel) != 0
sysvar(1) = floor(vel y)

[State 5110, 8]
type = VelSet
trigger1 = Time = 0
y = 0
x = 0

[State 5110, 9] ;For hit up type
type = ChangeAnim
persistent = 0
triggerall = anim = [5171,5179]
triggerall = SelfAnimExist(5110 + (anim % 10))
trigger1 = AnimTime = 0
trigger2 = SysVar(0) ;SysVar(0) = 1 avoids hit ground anim
value = 5110 + (anim % 10)

[State 5110, 10] ;For normal
type = ChangeAnim
persistent = 0
triggerall = Anim != [5111,5119]
trigger1 = AnimTime = 0
trigger2 = SysVar(0) ;SysVar(0) = 1 avoids hit ground frame
value = 5110

[State 5110, 11] ;If just died
type = ChangeState
triggerall = !alive
trigger1 = AnimTime = 0
trigger2 = SysVar(0) ;SysVar(0) = 1 avoids hit ground frame
trigger3 = Anim = [5110,5119]
value = 5150

[State 5110, 12]
type = VarSet
trigger1 = SysVar(0)
trigger1 = Time = 0
sysvar(0) = 0

[State 5110, 12]
type = VarSet
trigger1 = !Time
sysvar(4) = Const(data.liedown.time)

[State 5110, ChangeState]
type = ChangeState
triggerall = alive
trigger1 = time = 10
value = 5120
ctrl = 0

[State 5110, 14]
type = ForceFeedback
trigger1 = alive
trigger1 = Time = 0
time = 8
ampl = 240
waveform = sine

[State 5110, 15]
type = ForceFeedback
trigger1 = !alive
trigger1 = Time = 0
ampl = 200, 7, -.467
time = 30
waveform = sine
;---------------------------------------------------------------------------
; HIT_GETUP
[Statedef 5120]
type    = L
movetype= I
physics = N
sprpriority = 1

[State 5120, 1a] ;Get up anim (normal)
type = ChangeAnim
triggerall = time = 0
trigger1 = anim != [5111,5119]
trigger2 = !SelfAnimExist(5120 + (anim % 10))
value = 5120

[State 5120, 1b] ;Get up anim (for hit up/diag-up)
type = ChangeAnim
triggerall = time = 0
trigger1 = anim = [5111,5119]
trigger1 = SelfAnimExist(5120 + (anim % 10))
value = 5120 + (anim % 10)

[State 5120, 2]
type = VelSet
trigger1 = Time = 0
x = 0

[State 5120, 3]
type = NotHitBy
trigger1 = 1
value = SCA
time = 1

[State 5120, 4]
type = HitFallSet
trigger1 = AnimTime = 0
value = 1

[State 5120, 5] ;Can't be thrown right after getting up
type = NotHitBy
trigger1 = AnimTime = 0
value = , NT,ST,HT
time = 12

[State 5120, 6] ;Can't be hit right after getting up (short time)
type = NotHitBy
trigger1 = AnimTime = 0
value2 = SCA
time = 3

[State 5120, 7]
type = ChangeState
trigger1 = AnimTime = 0
value = 0
ctrl = 1

;---------------------------------------------------------------------------
; HIT_LIEDEAD
[Statedef 5150]
type    = L
movetype= H
physics = N
sprpriority = -1

[State 5150, 1]
type = ChangeAnim
triggerall = 1
trigger1 = Prevstateno = 8010
value = 6011

[State 5000, 1]
type = ChangeAnim
trigger1 = time >= 0
trigger1 = NumHelper(6969) = 1
trigger1 = Prevstateno != 8010
value = 25110

[State 5150, 1] ;Normal anim
type = ChangeAnim
triggerall = var(22) = 0
triggerall = Prevstateno != 8010
triggerall = Time = 0
triggerall = SelfAnimExist(5140)
trigger1 = (anim != [5111,5119]) && (anim != [5171,5179])
trigger2 = !SelfAnimExist(5140 + (anim % 10))
value = 5140

[State 5150, 3] ;Hit up type anim
type = ChangeAnim
triggerall = var(22) = 0
triggerall = Prevstateno != 8010
trigger1 = Time = 0
trigger1 = (anim = [5111,5119]) || (anim = [5171,5179])
trigger1 = SelfAnimExist(5140 + (anim % 10))
value = 5140 + (anim % 10)

[State 5150, 4] ;Match over anim
type = ChangeAnim
triggerall = var(22) = 0
triggerall = Prevstateno != 8010
persistent = 0
;trigger1 = Time = 0
trigger1 = MatchOver = 1
trigger1 = Anim = [5140,5149]
trigger1 = SelfAnimExist(anim+10)
value = anim+10

[State 5150, 5] ;Switch to 5110 if liedead anim does not exist
type = ChangeAnim
triggerall = var(22) = 0
triggerall = Prevstateno != 8010
trigger1 = Time = 0
trigger1 = Anim != [5140,5159]
trigger1 = Anim != [5110,5119]
value = 5110

[State 5150, 1] ;Normal anim
type = ChangeAnim
triggerall = var(22) != 0
triggerall = Prevstateno != 8010
triggerall = Time = 0
triggerall = SelfAnimExist(15140)
trigger1 = (anim != [15111,15119]) && (anim != [15171,15179])
trigger2 = !SelfAnimExist(15140 + (anim % 10))
value = 15140

[State 5150, 3] ;Hit up type anim
type = ChangeAnim
triggerall = var(22) != 0
triggerall = Prevstateno != 8010
trigger1 = Time = 0
trigger1 = (anim = [15111,15119]) || (anim = [15171,15179])
trigger1 = SelfAnimExist(15140 + (anim % 10))
value = 15140 + (anim % 10)

[State 5150, 4] ;Match over anim
type = ChangeAnim
triggerall = var(22) != 0
triggerall = Prevstateno != 8010
persistent = 0
;trigger1 = Time = 0
trigger1 = MatchOver = 1
trigger1 = Anim = [15140,15149]
trigger1 = SelfAnimExist(anim+10)
value = anim+10

[State 5150, 5] ;Switch to 5110 if liedead anim does not exist
type = ChangeAnim
triggerall = var(22) != 0
triggerall = Prevstateno != 8010
trigger1 = Time = 0
trigger1 = Anim != [15140,15159]
trigger1 = Anim != [15110,15119]
value = 15110

[State 5150, 6] ;Friction
type = VelMul
trigger1 = 1
x = 0.85

[State 5150, 7] ;Friction
type = VelSet
trigger1 = Vel x < .05
persistent = 0
x = 0

[State 5150, 8]
type = NotHitBy
trigger1 = 1
value = SCA
time = 1

;---------------------------------------------------------------------------
; HIT_FALLRECOVER (still falling)
[Statedef 5200]
type    = A
movetype= H
physics = N
sprpriority = 1

[State 5200, 1] ;Change anim if done with transition
type = ChangeAnim
trigger1 = Anim = 5035
trigger1 = AnimTime = 0
value = 5050

[State 5200, 2]
type = VelAdd
trigger1 = 1
y = GetHitVar(yaccel)

[State 5050, 5]; Recover in mid air
type = ChangeState
triggerall = Vel Y > -1
triggerall = alive
triggerall = CanRecover
trigger1 = Command = "recovery" && var(55) = 1
trigger2 = var(55) = 1 && random <= 300 && Pos Y < -20
value = 5210 ;HITFALL_AIRRECOVER

[State 5200, 3]
type = SelfState
trigger1 = Vel Y > 0
trigger1 = Pos Y >= 10
value = 5201

;---------------------------------------------------------------------------
; HIT_FALLRECOVER (on the ground)
[Statedef 5201]
type    = S
movetype= H
physics = S
anim = IfElse((Var(13) > 0),5201,5200)
velset = 0,0
sprpriority = 1

[State 5200]
type = Posset
trigger1 = time = 0
y = 0

[State 200, 音を鳴らす]
type = PlaySnd
trigger1 = AnimElem = 1
value = s10,18
channel = 4

[State 2110, 無敵]
type = NotHitBy
trigger1 = 1
value = SCA

[State 2110, ]
type = Varset
trigger1 = Animtime = 0
var(6) = 0

[State 2110, 移動量]
type = VelSet
trigger1 = AnimElemtime(1) >= 0 && AnimElemtime(6) <= 0
x = -4.8

[State 2110, 移動量]
type = VelSet
triggerall = var(6) = 1
trigger1 = AnimElemtime(2) >= 0 && AnimElemtime(7) <= 0
x = 6

;[State 2110, ]
;type = ChangeAnim
;triggerall = var(6) = 1
;trigger1 = time = 0
;value = 700

[State 2110, 移動終了]
type = VelSet
triggerall = var(6) = 0
trigger1 = AnimElem = 6
x = 0

[State 2110, 移動終了]
type = VelSet
triggerall = var(6) = 1
trigger1 = AnimElem = 7
x = 0

[State 2110, 相手と重なった時の処理]
type = PlayerPush
trigger1 = AnimElemTime(1) > 0
value = 0

[State 2110, 終了]
type = ChangeState
trigger1 = AnimTime = 0
value = 0
ctrl = 1

;---------------------------------------------------------------------------
; HIT_AIRFALLRECOVER
[Statedef 5210]
type    = A
movetype= I
physics = N
anim = IfElse((Var(13) > 0),5211,5210)
ctrl = 0
sprpriority = 1

[State 5210, 1] ;Blink white
type = PalFX
trigger1 = Time = 0
time = 3
add = 128,128,128 ;256,256,256

[State 5210, 1]
type = PosFreeze
trigger1 = Time = 0
value = 4

[State 5210, 2] ;Turn if not facing opponent
type = Turn
trigger1 = Time = 0
trigger1 = p2dist X < -20

[State 5210, 1]
type = VelMul
trigger1 = Time = 4
x = .8
y = .8

[State 5210, 1]
type = VelAdd
trigger1 = Time = 4
y = -4.5

[State 5210, 1]
type = VelMul
trigger1 = Time = 4
trigger1 = Vel Y > 0
y = .5

[State 5210, 1]
type = VelAdd
trigger1 = Time = 4
trigger1 = Vel Y > -3
y = -2

[State 5210, 1]
type = VelAdd
trigger1 = Time = 4
trigger1 = Vel Y > -2
y = -1

[State 5210, 2] ;Go up
type = VelAdd
trigger1 = Time = 4
trigger1 = Command = "holdup"
y = -2

[State 5210, 2] ;Go down
type = VelAdd
trigger1 = Time = 4
trigger1 = Command = "holddown"
y = 1.5

[State 5210, 2] ;Go fwd
type = VelMul
trigger1 = Time = 4
trigger1 = Command = "holdfwd"
x = 1

[State 5210, 2] ;Go back
type = VelAdd
trigger1 = Time = 4
trigger1 = Command = "holdback"
x = -1

[State 5210, 3]
type = NotHitBy
trigger1 = Time = 0
value = SCA
time = 15

[State 5210, 4]
type = CtrlSet
trigger1 = Time = 20
value = 1

[State 5210, 5]
type = VelAdd;Gravity
trigger1 = Time >= 4
y = .35

[State 5210, 5] ;Land on ground
type = ChangeState
trigger1 = Vel Y > 0
trigger1 = Pos Y >= 0
value = 52 ;JUMP_LAND
ctrl = 1

;---------------------------------------------------------------------------
; Continue?
[Statedef 5500]
type = S
ctrl = 0
anim = 5300
velset = 0,0

[State 5500, 1] ;Use continue animation if available
type = ChangeAnim
trigger1 = time = 0
trigger1 = SelfAnimExist(5500)
value = 5500

;---------------------------------------------------------------------------
; Initialize (at the start of the round)
[Statedef 5900]
type = S

[State 0, 1]
type = ChangeAnim
trigger1=Var(13)=1
trigger1 = (Anim !=8000) && Anim != 5
trigger2 = Anim = 5 && AnimTime = 0
value = 8000

[State 5900, 1]
type = varSet
trigger1 = time=0
var(13)=0

[State 5900, 1]
type = varSet
trigger1 = time=0
var(22)=0

[State 5900, 1] ;Clear all int variables
type = varRangeSet
trigger1 = roundno = 1
value = 0

[State 5900, 2] ;Clear all float variables
type = varRangeSet
trigger1 = roundno = 1
fvalue = 0

[State 5900, 3] ;Intro
type = ChangeState
trigger1 = roundno = 1
value = 190



