

[Remap]
x = x
y = y
z = z
a = a
b = b
c = c
s = s

;[Defaults]
; timeÇãLèqÇµÇ»Ç©Ç¡ÇΩèÍçáÅAà»â∫ÇÃílÇ™éQè∆Ç≥ÇÍÇ‹Ç∑ÅBç≈è¨ílÇÕ1Ç≈Ç∑ÅB
;command.time = 15

; buffer.timeÇÃílÇ≈Ç∑ÅB1Å`30Ç‹Ç≈ê›íËÇ≈Ç´Ç‹Ç∑ÅB
; ïÅí ÇÕ1Ç≈Ç∑ÅB
;command.buffer.time = 1

;-|AI Command |--------------------------------------------------------
[Command]
name = "CPU_1"
command = U,U,a,F,D,F,F,F,D,D,D,F,F,F,D,D,D
time = 1
[Command]
name = "CPU_2"
command = U,D,U,F,F,F,F,F,D,D,D,F,F,F,D,D,D
time = 1
[Command]
name = "CPU_3"
command = B,B,D,F,U,F,F,F,D,D,D,F,F,F,D,D,D
time = 1
[Command]
name = "CPU_4"
command = F,F,a,a,U,F,F,F,F,D,D,D,F,F,F,D,D,D
time = 1
[Command]
name = "CPU_5"
command = D,F,U,B,F,F,F,D,D,D,F,F,F,D,D,D
time = 1
[Command]
name = "CPU_6"
command = D,D,U,U,U,B,F,F,F,D,D,D,F,F,F,D,D,D
time = 1
[Command]
name = "CPU_7"
command = B,B,U,U,U,D,F,F,F,D,D,D,F,F,F,D,D,D
time = 1
[Command]
name = "CPU_8"
command = U,U,D,D,B,B,F,F,F,D,D,D,F,F,F,D,D,D
time = 1
[Command]
name = "CPU_9"
command = U,D,F,B,B,B,B,F,F,F,D,D,D,F,F,F,D,D,D
time = 1
[Command]
name = "CPU_10"
command = D,U,F,F,F,F,F,F,F,D,D,D,F,F,F,D,D,D
time = 1
[Command]
name = "CPU_11"
command = F,D,B,D,D,F,F,F,F,D,D,D,F,F,F,D,D,D
time = 1
[Command]
name = "CPU_12"
command = F,F,F,D,D,D,F,F,F,D,D,D,F,F,F,D,D,D
time = 1
[Command]
name = "CPU_13"
command = F,F,D,D,F,U,U,F,F,F,D,D,D,F,F,F,D,D,D
time = 1
[Command]
name = "CPU_14"
command = U,D,F,U,U,U,D,F,F,F,D,D,D,F,F,F,D,D,D
time = 1
[Command]
name = "CPU_15"
command = F,c,U,F,U,D,F,F,F,F,D,D,D,F,F,F,D,D,D
time = 1
[Command]
name = "CPU_16"
command = D,D,U,F,B,B,F,F,F,D,D,D,F,F,F,D,D,D
time = 1
[Command]
name = "CPU_17"
command = F,F,F,F,F,F,F,F,F,D,D,D,F,F,F,D,D,D
time = 1
[Command]
name = "CPU_18"
command = D,D,D,D,D,D,D,D,F,F,F,D,D,D,F,F,F,D,D,D
time = 1
[Command]
name = "CPU_19"
command = U,D,F,U,U,F,F,D,B,F,F,F,D,D,D,F,F,F,D,D,D
time = 1
[Command]
name = "CPU_20"
command = U,D,F,D,D,F,F,D,B,F,F,F,D,D,D,F,F,F,D,D,D
time = 1
[Command]
name = "CPU_21"
command = U,D,F,B,B,D,F,D,B,F,F,F,D,D,D,F,F,F,D,D,D
time = 1
[Command]
name = "CPU_22"
command = U,D,F,F,B,B,F,F,F,D,D,D,F,F,F,D,D,D
time = 1
[Command]
name = "CPU_23"
command = U,D,F,F,B,F,F,F,F,D,D,D,F,F,F,D,D,D
time = 1
[Command]
name = "CPU_24"
command = U,D,F,F,B,F,F,F,F,D,D,D,F,F,F,D,D,D
time = 1
[Command]
name = "CPU_25"
command = U,D,F,F,B,U,F,F,F,D,D,D,F,F,F,D,D,D
time = 1
[Command]
name = "CPU_26"
command = U,D,F,F,U,B,F,F,F,D,D,D,F,F,F,D,D,D
time = 1
[Command]
name = "CPU_27"
command = U,D,F,F,D,B,F,F,F,D,D,D,F,F,F,D,D,D
time = 1
[Command]
name = "CPU_28"
command = U,D,F,F,F,B,F,F,F,D,D,D,F,F,F,D,D,D
time = 1
[Command]
name = "CPU_29"
command = U,D,U,F,B,B,F,F,F,D,D,D,F,F,F,D,D,D
time = 1
[Command]
name = "CPU_30"
command = U,D,D,F,B,B,F,F,F,D,D,D,F,F,F,D,D,D
time = 1
[Command]
name = "CPU_31"
command = D,D,F,F,B,B,F,F,F,D,D,D,F,F,F,D,D,D
time = 1
[Command]
name = "CPU_32"
command = U,U,F,F,B,B,F,F,F,D,D,D,F,F,F,D,D,D
time = 1
[Command]
name = "CPU_33"
command = U,B,F,F,B,B,F,F,F,D,D,D,F,F,F,D,D,D
time = 1
[Command]
name = "CPU_34"
command = U,B,F,F,U,U,B,B,F,F,F,D,D,D,F,F,F,D,D,D
time = 1
[Command]
name = "CPU_35"
command = U,B,F,F,F,B,U,D,F,F,F,F,D,D,D,F,F,F,D,D,D
time = 1

;--------------------------------------------------------
;MI2 MAX
[Command]
name = "3500"
command = ~D, F, D, F, z
time = 30
buffer.time = 5

[Command]
name = "3500"
command = ~D, F, z
time = 20
buffer.time = 5

;Ãÿ ‚∏Ò¿ºÃÿπ•ª˜
[Command]
name = "3000"
command = ~D, B, D, B, b
time = 25
buffer.time = 5

[Command]
name = "3000"
command = ~D, B, D, B, b
buffer.time = 5

[Command]
name = "3000"
command = ~D, B, D, B, a
time = 25
buffer.time = 5

[Command]
name = "3000"
command = ~D, B, D, B, a
buffer.time = 5

;÷’Ω·∞¢∏˘Õ¢π•ª˜
[Command]
name = "3100"
command = ~D, B, D, B, y
time = 25
buffer.time = 5

[Command]
name = "3100"
command = ~D, B, D, B, y
buffer.time = 5

[Command]
name = "3100"
command = ~D, B, D, B, x
time = 25
buffer.time = 5

[Command]
name = "3100"
command = ~D, B, D, B, x
buffer.time = 5

; ∂”…±  ÷’Ω·∞¢∏˘Õ¢π•ª˜
[Command]
name = "3700"
command = ~D, B, D, B, c
time = 25
buffer.time = 5

[Command]
name = "3700"
command = ~D, B, D, B, c
buffer.time = 5

[Command]
name = "3700"
command = ~D, B, D, B, c
time = 20


;≈‹∂ØøÒª∂
[Command]
name = "3200"
command = ~D, F, D, F, a
time = 25
buffer.time = 5
[Command]
name = "3200"
command = ~D, F, D, F, b
time = 25
buffer.time = 5
;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;≥¨º∂∞¢∏˘Õ¢±≥À§
[Command]
name = "1000"
command = ~B, D, $DF, F, a
time = 15
buffer.time = 5
[Command]
name = "1000"
command = ~B, D, $DF, F, b
time = 15
buffer.time = 5
[Command]
name = "1000"
command = ~F, B, D, F, a
time = 15
buffer.time = 5
[Command]
name = "1000"
command = ~F, B, D, F, b
time = 15
buffer.time = 5

[Command]
name = "1000"
command = ~B, D, F, a
;time = 20
buffer.time = 5
[Command]
name = "1000"
command = ~B, D, F, b
;time = 20
buffer.time = 5

[Command]
name = "1000"
command = ~$DB, F, a
time = 15
buffer.time = 5
[Command]
name = "1000"
command = ~$DB, F, b
time = 15
buffer.time = 5
[Command]
name = "1000"
command = ~B, $D, F, $D, a
time = 15
buffer.time = 5
[Command]
name = "1000"
command = ~B, $D, F, $D, b
time = 15
buffer.time = 5
[Command]
name = "1000"
command = ~B, $D, F, $B, a
time = 15
buffer.time = 5
[Command]
name = "1000"
command = ~B, $D, F, $B, b
time = 15
buffer.time = 5
[Command]
name = "1000"
command = ~B, D, F, a
time = 15
buffer.time = 5
[Command]
name = "1000"
command = ~B, D, F, b
time = 15
buffer.time = 5
;∆Ô¬ÌÀ§
[Command]
name = "1100"
command = ~B, D, F, x
time = 15
buffer.time = 5
[Command]
name = "1100"
command = ~B, D, F, y
time = 15
buffer.time = 5
[Command]
name = "1100"
command = ~D, $DF, F, x
;time = 20
buffer.time = 5
[Command]
name = "1100"
command = ~D, $DF, F, y
;time = 20
buffer.time = 5

;π‚√˜œÚµº
[Command]
name = "1900"
command = ~F, D, B, x
time = 20
buffer.time = 5
[Command]
name = "1900"
command = ~F, D, B, y
time = 20
buffer.time = 5
[Command]
name = "1900"
command = ~D, $DB, B, x
time = 20
buffer.time = 5
[Command]
name = "1900"
command = ~D, $DB, B, y
time = 20
buffer.time = 5


;∏Ò¿ºÃÿπ•ª˜
[Command]
name = "1500"
command = ~25$B, F, x
;time = 20
buffer.time = 5

[Command]
name = "1501"
command = ~25$B, F, y
;time = 20
buffer.time = 5

[Command]
name = "1500"
command = ~25$DB, F, x
;time = 20
buffer.time = 5

[Command]
name = "1501"
command = ~25$DB, F, y
;time = 20
buffer.time = 5

;¡“ª…¡π‚÷‚
[Command]
name = "26xy"
command = ~D, $DF, F, x
;time = 15

[Command]
name = "26xy"
command = ~D, $DB, B, x

[Command]
name = "26xy"
command = ~D, $DF, F, y
;time = 15

[Command]
name = "26xy"
command = ~D, $DB, B, y

[Command]
name = "26ab"
command = ~D, $DF, F, a
;time = 15

[Command]
name = "26ab"
command = ~D, $DB, B, a

[Command]
name = "26ab"
command = ~D, $DF, F, b
;time = 15

[Command]
name = "26ab"
command = ~D, $DB, B, b

;∏•¿ºøœ±ÿ…±ºº
[Command]
name = "1400"
command = ~F, D, DF, a
time = 15
buffer.time = 5
[Command]
name = "1450"
command = ~F, D, DF, b
time = 15
buffer.time = 5
;[Command]
;name = "1400"
;command = ~B, D, DB, a

;[Command]
;name = "1450"
;command = ~B, D, DB, b


[Command]
name = "grab up 1"
command = ~D, D, x

[Command]
name = "grab up 2"
command = ~D, D, a

[Command]
name = "grab up 2"
command = ~D, D, b

[Command]
name = "grab up 3"
command = ~D, D, y


;ƒ˝πÃ∆˚”ÕµØ
[Command]
name = "1700"
command = ~F, D, DF, x
buffer.time = 5
[Command]
name = "1700"
command = ~F, D, DF, y
buffer.time = 5
;ƒÊœÚ°§ΩÿÀ§
[Command]
name = "1600"
command = ~D, D, $D, a
time = 20
buffer.time = 5
;ƒÊœÚ°§À≤…±
[Command]
name = "1650"
command = ~D, D, $D, b
time = 20
buffer.time = 5
;ƒÊœÚ°§R.K.O.
[Command]
name = "1690"
command = ~D, D, $D, x
time = 20
buffer.time = 5
;ƒÊœÚ°§…˙√¸ ±÷”
[Command]
name = "1680"
command = ~D, D, $D, y
time = 25
buffer.time = 5
;MI2°§Special
[Command]
name = "2000"
command = ~$D, B, z
;time = 25
buffer.time = 5

[Command]
name = "holdupfwd"
command = /UF
time = 1

[Command]
name = "longjump"
command = $D, $U
time = 12
buffer.time = 8



;-| ÇQâÒâüÇµãZ |-----------------------------------------------------------
[Command]
name = "FF"
command = F, F
time = 10
buffer.time = 1

[Command]
name = "BB"
command = B, B
time = 10
buffer.time = 1


;-------------------------------

[Command]
name = "a"
command = a
time = 1
buffer.time = 1

[Command]
name = "a1"
command = a
time = 1
command.buffer.time = 4

[Command]
name = "b"
command = b
time = 1
buffer.time = 1

[Command]
name = "c"
command = c
time = 1

[Command]
name = "x"
command = x
time = 1
buffer.time = 1

[Command]
name = "y"
command = y
time = 1
buffer.time = 1

[Command]
name = "z"
command = z
time = 1

[Command]
name = "start"
command = s
time = 1

;-----------------------------

[Command]
name = "recovery"
command = x+a
time = 1

;[Command]
;name = "recovery"
;command = z
;time = 1

[Command]
name = "by"
command = b+y
time = 1

;[Command]
;name = "by"
;command = c
;time = 1

;[Command]
;name = "a+b"
;command = a+b
;time = 1

;----------------------------------


[Command]
name = "UF"
command = UF
time = 1


;------------------------------------------------------------------------------
;-| ï˚å¸ÉLÅ[âüÇµÇ¡ÇœÇ»Çµ |-----------------------------------------------------
[Command]
name = "holdfwd"
command = /$F
time = 1
buffer.time = 1

[Command]
name = "back"
command = B
time = 1
buffer.time = 1


[Command]
name = "upback"
command = UB
time = 1

[Command]
name = "downback"
command = DB
time = 1

[Command]
name = "holdback"
command = /$B
time = 1
buffer.time = 1

[Command]
name = "holdup"
command = /$U
time = 1
buffer.time = 1

[Command]
name = "holddown"
command = /$D
time = 1
;command.buffer.time = 1

[Command]
name = "holdx"
command = /$x
time = 1

[Command]
name = "holdy"
command = /$y
time = 1

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[Command]
name = "throw1"
command = /F,y
time = 1

[Command]
name = "throw1"
command = /B,y
time = 1

[Command]
name = "throw2"
command = /F,b
time = 1

[Command]
name = "throw2"
command = /B,b
time = 1

[Command]
name = "throw3"
command = /D,b
time = 1

[Command]
name = "throw3"
command = /D,y
time = 1








[Statedef -1]

;;;;;;;;;;;;;;;;;;;;;;;;;

;Normal A.I.

[State -1]
type = ChangeState
value = 130
triggerall = p2movetype = A
triggerall = inguarddist;
triggerall = random <= 900
triggerall = statetype != A
triggerall = var(59) = 10
triggerall = ctrl
triggerall = stateno != 120
trigger1 = P2StateType != C
trigger2 = (Enemy, NumProj >= 1) || (Enemy, Numhelper >= 1)
trigger2 = inguarddist
;trigger3 = stateno = 102

; Stand to Crouch Guard
[State -1, AI Stand to Crouch Guard]
type = ChangeState
triggerall = NumEnemy
triggerall = RoundState = 2 && var(59) = 10
triggerall = StateType != A && Ctrl
triggerall = P2StateType = C || p2stateno = [400,490]
triggerall = (P2Movetype = A) || (Enemynear, NumProj > 1) || (Enemynear, Numhelper > 1)
trigger1 = StateNo = 150
trigger1 = 1
value = 152

; Crouch Guard
[State -1, AI Crouch Guard]
type = ChangeState
triggerall = P2Movetype = A
triggerall = inguarddist;
triggerall = RoundState = 2 && var(59) = 10
triggerall = StateType != A
triggerall = (Enemy, HitDefAttr = C,AA) || (p2stateno = [400,490])
triggerall = random <= 900
triggerall = Ctrl
trigger1 = P2StateType = C
;trigger2 = stateno = 102
value = 131

; Crouch to Stand Guard
[State -1, AI Crouch to Stand Guard]
type = ChangeState
;triggerall = NumEnemy
triggerall = RoundState = 2 && var(59) = 10
triggerall = StateType != A
triggerall = P2StateType != C
triggerall = (P2Movetype = A) || (Enemynear, NumProj > 1) || (Enemynear, Numhelper > 1)
trigger1 = StateNo = 152
trigger1 = 1
value = 150

; Jump Guard
;[State -1, AI Jump Guard]
;type = changestate
;;triggerall = NumEnemy
;triggerall = RoundState = 2 && var(59) = 10
;triggerall = StateType = A
;triggerall = (P2Movetype = A) || (Enemynear, NumProj > 1) || (Enemynear, Numhelper > 1) || (Enemy, HitDefAttr = SAC,HP)
;triggerall = stateno = 2041 && ctrl
;triggerall = stateno != 132
;trigger1 = ctrl
;trigger1 = random < 700
;trigger1 = P2StateType = A
;value = 132

[State -1]
type = ChangeState
value = 132
triggerall = p2movetype = A;access only when opponent attack
triggerall = inguarddist;P2bodydist X <= 40;access only when near
triggerall = P2life != 0;don't player when opponent had die
triggerall = statetype = A;perform when in air
triggerall = random <= 500;high percent
triggerall = var(59) = 10;only AI can access
triggerall = ctrl;make sure AI had control
triggerall = stateno != 132
trigger1 = p2statetype = A



[State -1];É_ÉbÉVÉÖ
type = ChangeState
value = 104
triggerall = var(59) = 10 && roundstate = 2
trigger1 = statetype != A
trigger1 = ctrl
trigger1 = StateNo != 104
;trigger1 = !(Enemynear, NumProj >= 1) || !(Enemynear, Numhelper >= 1)
;trigger1 = p2statetype != L; && p2movetype = H
trigger1 = p2statetype != A &&  p2movetype != A && p2stateno != 5120; && p2statetype != L
trigger1 = random > VAR(51) && p2bodydist X > 20  ;!inguarddist &&
;trigger2 = var(39) = 1 && p2statetype = A && p2bodydist X > 60 && p2movetype = H
;trigger2 = statetype != A
;trigger2 = ctrl
;trigger2 = StateNo != 104
;trigger2 = ;!inguarddist

[State -1,CFHP]
type = ChangeState
value = 215
triggerall = roundstate = 2 && var(59) = 10
trigger1 = p2bodydist x <= 30 && (Enemy, NumProj < 1) && stateno = 400 && animelem = 4, <0 && movehit && p2statetype != A && p2statetype != L
trigger2 = P2bodydist x <= 30 && (Enemy, NumProj < 1) && p2statetype != A && p2statetype != L && ctrl && statetype = S && p2stateno != 5120 && p2movetype != I

[State -1, Crouching Light Kick]
type = ChangeState
value = 400
triggerall = roundstate = 2 && var(59) = 10;only AI can access
trigger1 = (var(45) = 1) && P2bodydist X <= 40 && ctrl && p2statetype != A && p2statetype != L
trigger2 = P2bodydist X <= 35 && p2movetype != A && p2statetype != A && p2statetype != L && ctrl && statetype = S && p2stateno != 5120 && random < var(52)

[State -1,CFHP]
type = ChangeState
value = 301
triggerall = roundstate = 2 && var(59) = 10
trigger1 = p2bodydist x <= 30 && stateno = 215 && animelem = 4, <0 && movehit && p2statetype != A && p2statetype != L
trigger1 = random < 400

[State -1, Double Throw]
type = ChangeState
value = 1000
triggerall = roundstate = 2 && var(59) = 10
triggerall = statetype != A
trigger1 = !MoveGuarded
trigger1 =  StateNo = 104
trigger1 =  (p2bodydist X = [0,35]) && p2statetype != A && p2statetype != L && p2stateno != 5120

[State -1, Double Throw]
type = ChangeState
value = 1000
triggerall = roundstate = 2 && var(59) = 10
triggerall = statetype != A
trigger1 = stateno = 300
trigger1 = p2statetype != A && p2statetype != L
trigger1 = movehit
trigger1 = random <= 500
trigger2 = stateno = 215
trigger2 = animelem = 4, <0
trigger2 = movehit
trigger2 = p2statetype != A && p2statetype != L
trigger3 = stateno = 400
trigger3 = p2statetype != A && p2statetype != L
trigger3 = movehit
trigger3 = random <= 500
trigger4 = stateno = 205
trigger4 = animelem = 5, <0 && movehit
trigger4 = p2statetype != A && p2statetype != L
trigger5 = stateno = 235
trigger5 = movehit
trigger5 = p2statetype != A && p2statetype != L
trigger6 = stateno = 301
trigger6 = p2bodydist x <= 30 && p2statetype != A && p2statetype != L
trigger6 = animelem = 5, <0
trigger6 = movehit
trigger6 = random <= 100

[State -1,3100]
type = ChangeState
value = 3010
triggerall = power >= 2500
triggerall = roundstate = 2 && var(59) = 10
triggerall = statetype != A
trigger1 = p2bodydist x <= 60 && stateno = 1501 && (animelem = 9, >=0 && animelem = 10, <0) && movehit && p2statetype != A && p2statetype != L && p2life > 110
trigger2 = stateno = 215 && animelem = 4, <0 && movehit && p2statetype != A && p2statetype != L
trigger2 = random < 200
trigger3 = stateno = 400
trigger3 = p2statetype != A && p2statetype != L
trigger3 = movehit
trigger3 = random < 50
trigger4 = stateno = 205
trigger4 = animelem = 5, <0 && movehit
trigger4 = p2statetype != A && p2statetype != L
trigger5 = stateno = 235
trigger5 = movehit
trigger5 = p2statetype != A && p2statetype != L
trigger6 = stateno = 300
trigger6 = p2statetype != A && p2statetype != L
trigger6 = movehit
trigger6 = random < 100
trigger7 =  statetype != A  && ctrl
trigger7 =  (p2bodydist x = [15,30]) && p2movetype != H && p2statetype != L && p2stateno != 5120
trigger7 = random < 100

[State -1,3700]
type = ChangeState
value = 3700
triggerall = roundstate = 2 && var(59) = 10
triggerall = (power = [2000,3000)) && statetype != A
trigger1 = !MoveGuarded
trigger1 =  statetype != A  && ctrl || (StateNo = 104 && random <= 100)
trigger1 =  p2bodydist x <= 35 && p2statetype != A && p2statetype != L && p2stateno != 5120 && (p2stateno != [40,52])
trigger2 = stateno = 215
trigger2 = animelem = 4, <0
trigger2 = movehit
trigger2 = p2statetype != A && p2statetype != L
trigger3 = p2bodydist x <= 50 && (stateno = [3000,3010]) && (animelem = 15, >0 && animelem = 16, <0) && movehit && p2statetype != A && p2statetype != L
trigger4 = stateno = 205
trigger4 = animelem = 5, <0 && movehit
trigger4 = p2statetype != A && p2statetype != L
trigger5 = stateno = 235
trigger5 = movehit
trigger5 = p2statetype != A && p2statetype != L
trigger6 = stateno = 300
trigger6 = p2statetype != A && p2statetype != L
trigger6 = movehit
trigger6 = random <= 100
trigger7 = p2bodydist x <= 30 && stateno = 400 && movehit && p2statetype != A && p2statetype != L
trigger7 = random <= 500
trigger8 = stateno = 301
trigger8 = p2bodydist x <= 30 && p2statetype != A && p2statetype != L
trigger8 = animelem = 5, <0
trigger8 = movehit
trigger8 = random <= 100
trigger9 = p2bodydist x <= 30 && stateno = 1501 && (animelem = 9, >0 && animelem = 9, <3) && movehit && p2statetype != A && p2statetype != L && p2life > 400
;trigger10 = stateno = 102


[State -1,3100]
type = ChangeState
value = 3100
triggerall = power >= 1000
triggerall = roundstate = 2 && var(59) = 10
triggerall = statetype != A
trigger1 = !MoveGuarded
trigger1 =  statetype != A  && ctrl || (StateNo = 104 && random <= 200)
trigger1 =  p2bodydist x <= 35 && p2statetype != A && p2statetype != L && p2stateno != 5120 && (p2stateno != [40,52])
trigger2 = stateno = 215
trigger2 = animelem = 4, <0
trigger2 = movehit
trigger2 = p2statetype != A && p2statetype != L
trigger3 = stateno = 400
trigger3 = p2statetype != A && p2statetype != L
trigger3 = movehit
trigger3 = random <= 500
trigger4 = stateno = 205
trigger4 = animelem = 5, <0 && movehit
trigger4 = p2statetype != A && p2statetype != L
trigger5 = stateno = 235
trigger5 = movehit
trigger5 = p2statetype != A && p2statetype != L
trigger6 = stateno = 300
trigger6 = p2statetype != A && p2statetype != L
trigger6 = movehit
trigger6 = random <= 100
trigger7 = stateno = 301
trigger7 = p2bodydist x <= 30 && p2statetype != A && p2statetype != L
trigger7 = animelem = 5, <0
trigger7 = movehit
trigger7 = random <= 100
trigger8 = p2bodydist x <= 30 && stateno = 1501 && (animelem = 9, >0 && animelem = 9, <3) && movehit && p2statetype != A && p2statetype != L && p2life > 110

[State -1, RollFWD]
type = ChangeState
value = 700
triggerall = roundstate = 2 && var(59) = 10
triggerall = statetype != A; && (frontEdgeDist != [60,200])
triggerall = var(46) != 1
;trigger1 = ctrl || StateNo = 104
;trigger1 = p2movetype = A && (Enemy, vel x > 0) && random >= VAR(50) ;&& p2statetype != L && p2stateno != 5120
trigger1 = ((Enemy, NumProj >= 1) || (Enemy, Numhelper >= 1) || enemy, hitdefattr = SAC,HA,AP) && (random >= VAR(50))
trigger1 =  ctrl || StateNo = 104
trigger1 = (frontEdgeDist != [60,200]) && p2statetype != L && p2stateno != 5120
trigger2 = (backEdgeDist <= 40) && (enemy, hitdefattr = SAC,HA,AP) && inguarddist && (random >= 500) && ctrl

[State -1,ROLL BACK]
type = ChangeState
value = 710
triggerall = roundstate = 2 && var(59) = 10
triggerall = ctrl
trigger1 = statetype != A && ctrl
trigger1 = p2bodydist x <= 40 && p2statetype = L && backedgebodydist > 60 && random < 600


[State -1,3200]
type = ChangeState
value = 3200
triggerall = roundstate = 2 && var(59) = 10
triggerall = power >= 1000 && statetype != A && random >= VAR(50)
trigger1 = !MoveGuarded
trigger1 =  statetype != A  && ctrl
trigger1 =  (p2bodydist x = (60,90]) && p2statetype != A && p2statetype != L && p2stateno != 5120 && (p2stateno != [40,52]) && random >= VAR(50)
trigger1 = !(Enemy, HitDefAttr = SAC,HA,AP)
trigger2 = stateno = 215
trigger2 = animelem = 4, <0
trigger2 = movehit
trigger2 = p2statetype != A && p2statetype != L
trigger3 = stateno = 205
trigger3 = animelem = 5, <0 && movehit
trigger3 = p2statetype != A && p2statetype != L
trigger4 = stateno = 235
trigger4 = movehit
trigger4 = p2statetype != A && p2statetype != L
trigger5 = stateno = 300
trigger5 = p2statetype != A && p2statetype != L
trigger5 = movehit
trigger5 = random <= 100
trigger6 = stateno = 400
trigger6 = p2statetype != A && p2statetype != L
trigger6 = movehit
trigger6 = random <= 500
trigger7 = stateno = 301
trigger7 = p2bodydist x <= 30 && p2statetype != A && p2statetype != L
trigger7 = animelem = 5, <0
trigger7 = movehit
trigger7 = random <= 100
trigger8 = stateno = 1501
trigger8 = animelem = 9, >0 && animelem = 9, <3 && movehit
trigger8 = p2bodydist x <= 30 && p2statetype != A && p2statetype != L && p2life > 110

;[State -1,CFHP]
;type = ChangeState
;value = 240
;triggerall = roundstate = 2 && var(59) = 10
;triggerall = statetype = S && ctrl
;trigger1 = (p2bodydist x = [80,110])&& p2statetype != L && P2bodydist y > 50 && Enemynear,vel X > 0 && ctrl
;trigger2 = var(39) = 1 && p2statetype = A && (p2bodydist x = [0,90]) && p2movetype = H && power < 500

[State -1,5]
type = ChangeState
triggerall = var(59) = 10
triggerall = RoundState = 2
triggerall = statetype != A
triggerall = p2bodydist X = [80,120]
triggerall = p2statetype = A
triggerall = p2statetype != L
trigger1 = Enemynear,vel X > 0
Trigger1 = ctrl
trigger2 = p2bodydist X <= 60 && NumTarget(650) && ctrl && random <= 600
value = 240


[State -1,3200]
type = ChangeState
value = 1100
triggerall = roundstate = 2 && var(59) = 10
triggerall = statetype != A
trigger1 = stateno = 300 && animelem = 5, <0 && movehit && p2statetype != A && p2statetype != L; && random >= 500
trigger2 = stateno = 215 && animelem = 4, <0 && movehit && p2statetype != A && p2statetype != L
trigger2 = random < 500
trigger3 = stateno = 400
trigger3 = p2statetype != A && p2statetype != L
trigger3 = movehit
trigger3 = random < 50
trigger4 = stateno = 205
trigger4 = animelem = 5, <0 && movehit
trigger4 = p2statetype != A && p2statetype != L
trigger5 = stateno = 235
trigger5 = movehit
trigger5 = p2statetype != A && p2statetype != L

[State -1]
type = ChangeState
value = 1501
triggerall = roundstate = 2 && var(59) = 10
triggerall = statetype != A
trigger1 = stateno = 301 && animelem = 5, <0 && movehit && p2statetype != A && p2statetype != L ;p2bodydist x <= 35 &&
;trigger1 = random < 500
trigger2 = stateno = 215 && animelem = 4, <0 && movehit && p2statetype != A && p2statetype != L
trigger2 = random < 400
;trigger3 =  statetype != A  && ctrl
;trigger3 = !(Enemy, HitDefAttr = SAC,AP)
;trigger3 = (p2bodydist x = [20,50]) && p2statetype = A && p2movetype != H ; && (p2bodydist Y = [-50,-30])
;trigger3 = p2statetype != L && p2stateno != 5120 && (p2stateno != [120,155]) && (p2stateno != 40)
trigger3 = stateno = 200
trigger3 = p2statetype != A && p2statetype != L
trigger3 = movehit
trigger4 = stateno = 235
trigger4 = p2statetype != A && p2statetype != L
trigger4 = movehit
trigger5 = p2bodydist x <= 30 && stateno = 300  && movehit && p2statetype != A && p2statetype != L
trigger6 = stateno = 400
trigger6 = p2statetype != A && p2statetype != L
trigger6 = movehit


;[State -1,3100]
;type = ChangeState
;value = 3000
;triggerall = power = [1000,2000)
;triggerall = roundstate = 2 && var(59) = 10
;triggerall = statetype != A
;trigger1 = stateno = 1101 && movecontact && p2statetype != A && p2statetype != L


[State -1];é„ÇfÅEÉNÉåÉCÉX
type = ChangeState
value = 3500
triggerall = var(59) = 10; && roundstate = 2
triggerall = statetype != A && ctrl
triggerall = power >=1500
trigger1 = statetype != A && ctrl
trigger1 = p2bodydist X = [-5,70]
trigger1 = p2bodydist Y = [-140,-60]
trigger1 = random <= 700
trigger1 = p2statetype = A && p2statetype != L && p2stateno != 5120 ;(p2statetype = A || (p2statetype = A && p2movetype = H))
;trigger2 = p2movetype = A || target,time > 30
;trigger2 = p2statetype = A || (p2statetype = A && p2movetype = H)
trigger2 = stateno = 1500;  && movehit
trigger2 = (Animelemtime(12) > 0 && Animelemtime(13) < 1) && movehit
;trigger3 = stateno = 1501;  && movehit
;trigger3 = animelem = 14, >=0 && animelem = 15, <0 && movehit
;trigger4 = stateno = 102

[State -1,jumpHk]
type = ChangeState
value = 600
triggerall = P2life != 0;don't player when opponent had die
triggerall = roundstate = 2 && var(59) = 10;only AI can access
triggerall = statetype = A
triggerall = p2bodydist x <= 40 && P2statetype != A;(p2bodydist Y = [-140,-60])
triggerall = vel y >= .46;3;-1
triggerall = vel x >= .5
triggerall = ctrl
trigger1 = vel x != 0
trigger2 = vel y > .47 && stateno = 2041 && ctrl && P2statetype != A;bodydist y <= -10  ;vel y > .45

[State -1,27]
type = ChangeState
value = 440
triggerall = roundstate = 2 && var(59) = 10
triggerall = p2life != 0
trigger1 = statetype = S
trigger1 = ctrl = 1
trigger1 = P2statetype = S
trigger1 = (P2BodyDist X = (15,60)) && ((p2stateno != [700,900]) || p2stateno = 40 || p2stateno = 52)
trigger1 = random  < var(52)


[State -1]
type = ChangeState
value = 2000
triggerall = var(59) = 10 && roundstate = 2
triggerall = power = [500,1000)
triggerall =  statetype != A  && ctrl
trigger1 = statetype != A && ctrl
trigger1 = p2bodydist x <= 40; && p2statetype != L
trigger1 = p2stateno != 5120;player is not in getup state
trigger1 = random < 400;Very high percent
trigger1 =  P2MoveType = A
trigger2 =  backEdgeDist <= 40
trigger2 =  (P2MoveType = A) && (enemynear, hitdefattr = SAC,AA,AT) && (p2bodydist x = [40,80])
;trigger2 =  random <= 600
trigger3 =  p2life > 0
trigger3 =  p2movetype = H
trigger3 =  ((p2bodydist x = [10,45]) || (frontEdgeDist <= 50)) && (p2statetype = A || p2statetype = L) && p2stateno != 5120
trigger3 =  random > 750
;trigger4 = stateno = 102

[State -1, Taunt]
type = ChangeState
value = 2000
triggerall = roundstate = 3 && var(59) = 10
triggerall = statetype != A
triggerall = power = [500,1000)
;trigger1 = stateno != 195
trigger1 = alive
trigger1 = p2life <= 0  && ctrl && random > 600
trigger1 =  (p2bodydist x = [10,60]) && (p2statetype = A || p2statetype = L)


[State -1]
type = ChangeState
value = 650
triggerall = statetype = A
triggerall = roundstate = 2 && var(59) = 10 && ctrl
triggerall = random <= 600
triggerall= p2statetype = S
trigger1 = p2bodydist x = (19,38)
trigger2 = p2movetype = A
trigger2 = p2bodydist x = (-20,75) ; [-20,60]
trigger3 = p2bodydist X = [40,90]
trigger4 = vel x = 0
trigger5 = P2bodydist X = [20,120]
trigger5 = p2movetype = H && p2statetype = A

[State -1]
type = ChangeState
value = ifelse(random <= 600,1690,1685)
triggerall = roundstate = 2 && var(59) = 10
triggerall =  statetype != A  && ctrl && random < VAR(51) && (p2bodydist x = [-60,60])
trigger1 =  statetype != A  && ctrl; || StateNo = 104
;trigger1 = !(Enemy, HitDefAttr = SAC, AT,AP)
trigger1 =  backEdgeDist <= 50 && P2MoveType = A && p2statetype != A && p2statetype != L && p2stateno != 5120 && (p2bodydist x = [0,60])
;trigger1 =  p2statetype != L && p2stateno != 5120 && (p2stateno != [120,155]) && (p2stateno != 40)
trigger1 =  random <= 400
trigger2 =  (p2bodydist x = (-150,-60)) && p2statetype != A && p2statetype != L && p2stateno != 5120 && ctrl
trigger2 = random < 400
trigger3 = random > VAR(51) && (p2bodydist x = [-60,60]) && ctrl && (enemynear, hitdefattr = SC,AA) && p2statetype != A && p2statetype != L && p2stateno != 5120 && (p2stateno != [40,50]);var(46) = 1
trigger4 = var(46) = 1 && ctrl && p2statetype != A && p2statetype != L && p2stateno != 5120 && (Enemynear, NumProj < 1)
trigger5 = stateno = 215
trigger5 = animelem = 4, >=0 && movehit
trigger5 = p2statetype != A && p2statetype != L
;trigger5 = random <= 700
;trigger4 = p2bodydist x <= 130 && (random < VAR(51)) && p2statetype != A && p2statetype != L && p2stateno != 5120 && ctrl



[State -1]
type = ChangeState
value = ifelse(random <= 600,1680,1600)
triggerall = roundstate = 2 && var(59) = 10
triggerall = statetype != A && ctrl; && random < VAR(51) && (p2bodydist x = [-60,60])
trigger1 =  statetype != A  && ctrl; || StateNo = 104
trigger1 = backEdgeDist <= 50 && P2MoveType = A && p2statetype != A && p2statetype != L && p2stateno != 5120 && (p2bodydist x = [0,60])
trigger1 =  random < 400
trigger2 =  (p2bodydist x = (-150,-40)) && p2statetype != A && p2statetype != L && p2stateno != 5120 && ctrl
trigger2 = random > 600
trigger3 = random > VAR(51) && (p2bodydist x = [-60,60]) && ctrl && (enemynear, hitdefattr = SC,AA) && p2statetype != A && p2statetype != L && p2stateno != 5120 && (p2stateno != [40,50]);var(46) = 1
trigger4 = var(46) = 1 && ctrl && p2statetype != A && p2statetype != L && p2stateno != 5120 && (Enemynear, NumProj < 1); && (p2bodydist x = [-60,60])
trigger5 = stateno = 215
trigger5 = animelem = 4, >=0 && movehit
trigger5 = p2statetype != A && p2statetype != L
;trigger5 = random >= 200
trigger6 = stateno = 300
trigger6 = movehit
trigger6 = p2statetype != A && p2statetype != L
;trigger5 = p2bodydist x <= 130 && (random < VAR(51)) && p2statetype != A && p2statetype != L && p2stateno != 5120 && ctrl


;trigger4 = stateno = 102
;trigger6 = (enemy,numproj = 0) && (EnemyNear,statetype != L) && p2stateno != [120,155]
;trigger7 = (enemy,numhelper = 0) && (EnemyNear,statetype != L) && p2stateno != [120,155]

[State -1, Double Throw]
type = ChangeState
value = ifelse(random <= 600,1450,1400)
triggerall = roundstate = 2 && var(59) = 10
triggerall = statetype != A
trigger1 = !MoveGuarded
trigger1 =  statetype != A  && ctrl
trigger1 =  (p2bodydist x = [-20,20]) && p2statetype != A && p2statetype != L && p2movetype != H && (p2stateno != [40,50]); || p2stateno = [120,159]); && random < 600


[State -1]
type = ChangeState
value = 1700
triggerall = roundstate = 2 && var(59) = 10
triggerall = statetype != A
;trigger1 = stateno = 1501 && movehit && (animelem = 11, >0 && animelem = 12, <4) && movehit && p2statetype != L
trigger1 =  ((p2bodydist x = [40,60]) && (p2bodydist Y = [-140,-60])) && p2statetype = A && p2statetype != L && p2stateno != 5120 && ctrl
trigger1 = random < 100;medium percent
;trigger1 = !MoveGuarded
;trigger2 = stateno = 102



[State -1, AI Guard Cancel Blowback Attack]
type = ChangeState
triggerall = NumEnemy
triggerall = RoundState = 2 && var(59) = 10
triggerall = Power >= 1000 && StateType != A
triggerall = P2BodyDist x <= 30
trigger1 = (stateno = 150 || stateno = 152)
trigger1 = ifelse(life > 300, random < 20, random >= 500)
value = 260


;[State -1, JUMP]
;type = ChangeState
;value = 40
;triggerall = var(9) = 1
;triggerall = statetype != A && ctrl && p2movetype != H
;trigger1 = (p2bodydist x = [0,85]) && p2statetype = C && p2movetype != A && random <= 200
;trigger2 = p2statetype = S && (P2Movetype = A) || (Enemy, NumProj >= 1)
;trigger2 = P2bodydist X >= 60
;trigger2 = random < 200

[State -1,8]  ;tanjump
type = ChangeState
value = 40
triggerall = stateno != 40
triggerall = P2life != 0;don't player when opponent had die
triggerall = statetype != A;perform when not in air
triggerall = roundstate = 2 && var(59) = 10;only AI can access
triggerall = p2statetype != A
triggerall = !(Enemy, HitDefAttr = SAC,HA,HP)
triggerall = (frontedgebodydist = [40,80]) && (random > VAR(51))
triggerall = p2movetype != H
triggerall = ctrl
trigger1 = p2stateno = 5120;player is in getup state
trigger1 = P2bodydist X = [0,50]
trigger1 = random > VAR(51);random <= 100;high percent
trigger1 = statetype = S
;trigger2 = random > VAR(51);random <= 400;high percent
;trigger2 = P2bodydist X = [20,80]
;trigger2 = p2statetype = L
;trigger2 = statetype = S
trigger2 = p2bodydist x = [0,30]
trigger2 = random > VAR(51);random <=400
trigger2 = p2movetype != H
trigger3 = p2bodydist x = [0,50]
trigger3 = random > VAR(51);random <= 1000
trigger3 = p2statetype = C
trigger3 = p2movetype != H
trigger4 = (backEdgeDist <= 40) && p2statetype != A && !inguarddist && (random >= 500) && ctrl
;trigger6 = random <= 400;high percent
trigger5 = (P2bodydist X = [60,120]) && p2movetype = H && p2statetype = A


[State -1,JHKD/JHPD]
type = ChangeState
value = 640
triggerall = roundstate = 2 && var(59) = 10
triggerall = random <= 500 && statetype = A
triggerall = (p2bodydist x = (10,80)) && p2statetype = A && ctrl
trigger1 = (P2bodydist y = [-100,-30]) && ctrl && p2statetype = A;vel y > 0
trigger2 = vel y > .43 && stateno = 2041 && ctrl

[State -1,JHKD/JHPD]
type = ChangeState
value = 630
triggerall = roundstate = 2 && var(59) = 10
triggerall = random <= 200 && statetype = A
triggerall = p2bodydist x <= 30 && ctrl && p2movetype = A && p2statetype = A
trigger1 = vel y > 0 && ctrl
trigger2 = vel y > .46 && stateno = 2041 && ctrl

[State -1,JLK]
type = ChangeState
value = 610
triggerall = roundstate = 2 && var(59) = 10
triggerall = random <= 200 && statetype = A
triggerall = p2bodydist x <= 30 && p2movetype = A && p2statetype = A
trigger1 = vel y > 0 && ctrl
trigger2 = vel y > .46 && stateno = 2041 && ctrl

;[State -1]
;type = ChangeState
;value = 10
;triggerall = statetype = S
;triggerall = roundstate = 2 && var(59) = 10;only AI can access
;triggerall = P2bodydist X <= 25
;triggerall = ctrl
;triggerall = random <= 400;Medium Low percent
;trigger1 = p2movetype = H
;trigger1 = p2statetype = S
;trigger2 = p2movetype = H
;trigger2 = p2statetype = C

[State -1]
type = ChangeState
value = 0
triggerall = roundstate = 2 && var(59) = 10;Only AI can access
triggerall = random <= 100;very low percent
triggerall = stateno = 5300
trigger1 = time >= 80
ctrl = 1

; Do Recover near ground
[State -1]
type = ChangeState
value = 52000
triggerall = roundstate = 2 && var(59) = 10;Only AI can access
triggerall = random <= 900;high percent
triggerall = CanRecover
trigger1 = p2bodydist X >= 45
trigger1 = Vel Y > 0
trigger1 = pos y > -10
trigger1 = alive
trigger1 = (stateno = [5050,5060])
trigger2 = Vel Y > 0
trigger2 = pos y > -10
trigger2 = alive
trigger2 = (stateno = [5050,5060])
trigger2 = p2bodydist X < 45
trigger2 = p2movetype != A

[State -2]
type = ChangeState
value = 52000
triggerall = Vel Y > 0 && alive && var(59) = 10
trigger1 = (Pos Y = [-15,0]) && stateno = 5071

;[State -1,RUN]
;type = ChangeState
;value = 100
;triggerall = roundstate = 2 && var(59) = 10
;triggerall = stateno != 100 && statetype = S && ctrl
;trigger1 = p2bodydist x > 10 && p2statetype != L && p2movetype != A && random < 500

[State -1];ÉoÉbÉNÉXÉeÉbÉv
type = ChangeState
value = 105
triggerall = (var(59) = 10) && roundstate = 2
trigger1 = statetype != A
trigger1 = ctrl = 1
trigger1 = StateNo != 104
trigger1 = p2statetype = L
trigger1 = p2bodydist X = [-5,20]
trigger1 = backedgebodydist > 10
trigger1 = random < 600

[State -1]
type = ChangeState
value = 870
triggerall = statetype = A
triggerall = ctrl
triggerall = random < 500
triggerall = p2bodydist X < 6
triggerall = p2bodydist Y > -20 && p2statetype = A
triggerall = p2bodydist Y < 20
triggerall = roundstate = 2 && var(59) = 10;only AI can access
trigger1 = p2statetype = A
trigger1 = p2movetype != H

[State -1,Grab]
type = ChangeState
value = 800
triggerall = p2stateno != 131 && p2stateno != 130 && P2bodydist X <= 50 && random < 300 &&  var(59) = 10 && statetype != A && p2statetype != A && p2statetype != L && p2stateno != 5120
trigger1 = P2Dist x <= 50 && p2statetype != A && (p2movetype = I || (p2stateno = [300,900])) && ctrl
;trigger2 = stateno = 102 && time >= 3

[State -1,Grab]
type = ChangeState
value = 860
triggerall = p2stateno != 131 && p2stateno != 130 && P2bodydist X <= 50 && random < 300 &&  var(59) = 10 && statetype != A && p2statetype != A && p2statetype != L && p2stateno != 5120
trigger1 = P2Dist x <= 50 && p2statetype != A && (p2movetype = I || (p2stateno = [300,900])) && ctrl
;trigger2 = stateno = 102 && time >= 3

[State -1, Taunt]
type = ChangeState
value = 195
triggerall = var(59) = 10 && var(19) < 1 && random > 990
trigger1 = p2life = 0;roundstate = 3
trigger1 = statetype != A
trigger1 = stateno != 195; || stateno != 2000
trigger1 = alive
trigger1 = ctrl
;trigger1 = random < 50

;[State -1]
;type = ChangeState
;value = 3500
;triggerall = roundstate = 2 && var(59) = 10;only AI can access
;triggerall = p2statetype != L;player not lying down
;triggerall = p2stateno != 5120;player is not in getup state
;triggerall = power >= 1500
;triggerall = ifelse(life >=500,random <= 500,random <= 800);Very high percent
;triggerall = statetype != A
;triggerall = p2bodydist x <= 30
;triggerall = p2statetype = A
;trigger1 = ctrl
;trigger2 = stateno = 102



;--------------------
;--------------
;;;;;;;;;;;;;;

[State -1]
type = ChangeState
value = 3000
triggerall = !var(59)
triggerall = command = "3000"
triggerall = power >= 1000
triggerall = statetype != A
triggerall = stateno = 1101
trigger1 = movecontact

[State -1]
type = ChangeState
value = 3010
triggerall = !var(59)
triggerall = command = "3000"
triggerall = statetype != A
triggerall = power >= 1000
trigger1 = ctrl
trigger2 = (stateno = 100 && time > 3)
trigger3 = stateno = 200
;trigger3 = animelem = 4, <0
trigger3 = movecontact
trigger4 = stateno = 215
trigger4 = animelem = 4, <0
trigger4 = movecontact
trigger5 = stateno = 210
;trigger5 = animelem = 5, <0
trigger5 = movecontact
trigger6 = stateno = 235
;trigger6 = animelem = 3, <0
trigger6 = movecontact
trigger7 = stateno = 300
trigger7 = movecontact
trigger8 = stateno = 400
;trigger8 = animelem = 4, <0
trigger8 = movecontact
trigger9 = stateno = 301
trigger9 = movecontact
trigger10 = stateno = 410 && movecontact = 1
trigger11 = stateno = 1500
trigger11 = animelem = 4, >0 && animelem = 10, <3
trigger11 = movecontact
trigger12 = stateno = 1501
trigger12 = animelem = 4, >0 && animelem = 10, <3
trigger12 = movecontact
;trigger13 = stateno = 1101 && movecontact = 1

[State -1]
type = ChangeState
value = 3700
triggerall = !var(59)
triggerall = command = "3700"
triggerall = statetype != A
triggerall = power >= 2000
trigger1 = ctrl
trigger2 = (stateno = 100 && time > 3)
trigger3 = stateno = 200
;trigger3 = animelem = 4, <0
trigger3 = movecontact
trigger4 = stateno = 215
;trigger4 = animelem = 4, <0
trigger4 = movecontact
trigger5 = stateno = 1500
trigger5 = animelem = 4, >0 && animelem = 10, <3
trigger5 = movecontact
trigger6 = stateno = 235
;trigger6 = animelem = 3, <0
trigger6 = movecontact
trigger7 = stateno = 300
trigger7 = movecontact
trigger8 = stateno = 400
;trigger8 = animelem = 4, <0
trigger8 = movecontact
trigger9 = stateno = 301
trigger9 = movecontact
trigger10 = stateno = 410 && movecontact = 1
trigger11 = stateno = 1501
trigger11 = animelem = 4, >0 && animelem = 10, <3
trigger11 = movecontact
trigger12 = stateno = 3000 || stateno = 3010
trigger12 = animelem = 3, >0 && animelem = 15, <3
trigger12 = movecontact

[State -1]
type = ChangeState
value = 3100
triggerall = !var(59)
triggerall = command = "3100"
triggerall = statetype != A
triggerall = power >= 1000
trigger1 = ctrl
trigger2 = (stateno = 100 && time > 3)
trigger3 = stateno = 200
;trigger3 = animelem = 4, <0
trigger3 = movecontact
trigger4 = stateno = 215
;trigger4 = animelem = 4, <0
trigger4 = movecontact
trigger5 = stateno = 1500
trigger5 = animelem = 4, >0 && animelem = 10, <3
trigger5 = movecontact
trigger6 = stateno = 235
;trigger6 = animelem = 3, <0
trigger6 = movecontact
trigger7 = stateno = 300
trigger7 = movecontact
trigger8 = stateno = 400
;trigger8 = animelem = 4, <0
trigger8 = movecontact
trigger9 = stateno = 301
trigger9 = movecontact
trigger10 = stateno = 410 && movecontact = 1
trigger11 = stateno = 1501
trigger11 = animelem = 4, >0 && animelem = 10, <3
trigger11 = movecontact

[State -1]
type = ChangeState
value = 3200
triggerall = !var(59)
triggerall = command = "3200"
triggerall = statetype != A
triggerall = power >= 1000
trigger1 = ctrl
trigger2 = (stateno = 100 && time > 3)
trigger3 = stateno = 200
;trigger3 = animelem = 4, <0
trigger3 = movecontact
trigger4 = stateno = 215
trigger4 = animelem = 4, <0
trigger4 = movecontact
trigger5 = stateno = 1500
trigger5 = animelem = 4, >0 && animelem = 10, <3
trigger5 = movecontact
trigger6 = stateno = 235
;trigger6 = animelem = 3, <0
trigger6 = movecontact
trigger7 = stateno = 300
trigger7 = movecontact
trigger8 = stateno = 400
;trigger8 = animelem = 4, <0
trigger8 = movecontact
trigger9 = stateno = 301
trigger9 = movecontact
trigger10 = stateno = 410 && movecontact = 1
trigger11 = stateno = 1501
trigger11 = animelem = 4, >0 && animelem = 10, <3
trigger11 = movecontact

[State -1]
type = ChangeState
value = 3500
triggerall = !var(59)
triggerall = command = "3500"
triggerall = statetype != A
triggerall = power >= 1500
trigger1 = ctrl


;------------------------------------------------------------------------------



[State -1]
type = ChangeState
value = 2000
triggerall = !var(59)
triggerall = command = "2000"
triggerall = statetype != A
triggerall = power >= 500
trigger1 = ctrl
trigger2 = (stateno = 100 && time > 3)
;trigger3 = stateno = 200
;trigger3 = animelem = 3, >0
;trigger4 = stateno = 215
;trigger4 = animelem = 4, >0
;trigger5 = stateno = 210
;trigger5 = animelem = 3, >0
;trigger6 = stateno = 235
;trigger6 = animelem = 2, >0
;trigger7 = stateno = 300
;trigger8 = stateno = 400
;trigger9 = stateno = 230
;trigger10 = stateno = 230
;trigger11 = stateno = 240
;trigger12 = stateno = 250




[State -1]
type = ChangeState
value = 1700
triggerall = !var(59)
triggerall = command = "1700"
triggerall = statetype != A
trigger1 = ctrl
;trigger2 = (stateno = 100 && time > 3)
trigger2 = stateno = 200
;trigger2 = animelem = 4, <0
trigger2 = movecontact
;trigger3 = stateno = 215
;trigger3 = animelem = 4, <0
;trigger3 = movecontact
trigger4 = stateno = 210
;trigger4 = animelem = 5, <0
trigger4 = movecontact
trigger5 = stateno = 235
;trigger5 = animelem = 2, <0
trigger5 = movecontact
trigger6 = stateno = 300
trigger6 = movecontact
;trigger7 = stateno = 400
;trigger7 = animelem = 3, <0
;trigger7 = movecontact

[State -1]
type = ChangeState
value = 1680
triggerall = !var(59)
triggerall = command = "1680"
triggerall = statetype != A
trigger1 = ctrl

[State -1]
type = ChangeState
value = 1690
triggerall = !var(59)
triggerall = command = "1690"
triggerall = statetype != A
trigger1 = ctrl
trigger2 = stateno = 301
trigger2 = movecontact
trigger3 = stateno = 215
trigger3 = animelem = 4, <0
trigger3 = movecontact

[State -1]
type = ChangeState
value = 1685
triggerall = !var(59)
triggerall = command = "1650"
triggerall = statetype != A
trigger1 = ctrl

[State -1]
type = ChangeState
value = 1600
triggerall = !var(59)
triggerall = command = "1600"
triggerall = statetype != A
trigger1 = ctrl

[State -1]
type = ChangeState
value = 1900
triggerall = !var(59)
triggerall = command = "1900"
triggerall = statetype != A
trigger1 = ctrl
trigger2 = (stateno = 100 && time > 3)
trigger3 = stateno = 205 && movecontact = 1
trigger4 = stateno = 215
trigger4 = animelem = 4, <0
trigger4 = movecontact
trigger5 = stateno = 235
trigger5 = movecontact
trigger6 = stateno = 301
trigger6 = movecontact
trigger7 = stateno = 400
trigger7 = movecontact

[State -1]
type = ChangeState
value = 1500
triggerall = !var(59)
triggerall = (command = "1500" && command != "a" && command != "1100")
triggerall = statetype != A
trigger1 = ctrl
;trigger2 = (stateno = 100 && time > 3)
trigger3 = stateno = 200
;trigger3 = animelem = 4, <0
trigger3 = movecontact
trigger4 = stateno = 215
trigger4 = animelem = 4, <0
trigger4 = movecontact
trigger5 = stateno = 430
;trigger5 = animelem = 5, <0
trigger5 = movecontact
trigger6 = stateno = 235
;trigger6 = animelem = 2, <0
trigger6 = movecontact
trigger7 = stateno = 300
trigger7 = movecontact
trigger8 = stateno = 400
trigger8 = animelem = 3, <0
trigger8 = movecontact
trigger9 = stateno = 301
trigger9 = movecontact

[State -1]
type = ChangeState
value = 1501
triggerall = !var(59)
triggerall = (command = "1501" && command != "a" && command != "1100")
triggerall = command = "1501"
triggerall = statetype != A
trigger1 = ctrl
trigger2 = (stateno = 100 && time > 3)
trigger3 = stateno = 200
;trigger3 = animelem = 4, <0
trigger3 = movecontact
trigger4 = stateno = 215
trigger4 = animelem = 4, <0
trigger4 = movecontact
trigger5 = stateno = 210
;trigger5 = animelem = 5, <0
trigger5 = movecontact
trigger6 = stateno = 235
;trigger6 = animelem = 2, <0
trigger6 = movecontact
trigger7 = stateno = 300
trigger7 = movecontact
trigger8 = stateno = 400
;trigger8 = animelem = 3, <0
trigger8 = movecontact
trigger9 = stateno = 301
trigger9 = movecontact

[State -1]
type = ChangeState
value = 1000
triggerall = !var(59)
triggerall = command = "1000"
;triggerall = (command = "1000" && command != "x")
triggerall = statetype != A
trigger1 = ctrl
trigger2 = ((stateno = [100,102]) && time > 1)
trigger3 = stateno = 200 || stateno = 205;&& movecontact = 1
trigger3 = animelem = 3, >0 && animelem = 5, <0
trigger4 = stateno = 215
trigger4 = animelem = 1, >0 && animelem = 4, <0
trigger4 = movecontact
trigger5 = stateno = 235
trigger5 = movecontact
trigger6 = stateno = 300
;trigger6 = animelem = 5, <0
trigger6 = movecontact
trigger7 = stateno = 400
trigger7 = movecontact
trigger8 = stateno = 301
trigger8 = animelem = 5, <0
trigger8 = movecontact

[State -1]
type = ChangeState
value = 1100
triggerall = !var(59)
triggerall = command = "1100"
triggerall = statetype != A
trigger1 = ctrl
trigger2 = (stateno = 100 && time > 3)
trigger3 = (stateno = [200,205]) && movecontact
trigger4 = stateno = 215
trigger4 = animelem = 4, <0
trigger4 = movecontact
trigger5 = stateno = 235
trigger5 = movecontact
trigger6 = stateno = 301
trigger6 = movecontact
trigger7 = stateno = 400
trigger7 = movecontact

[State -1]
type = ChangeState
value = 1400
triggerall = !var(59)
triggerall = (command = "1400" && command != "1000")
triggerall = statetype != A
;triggerall = (stateno = 100 && time > 1)
trigger1 = ctrl
;trigger2 = (stateno = 100 && time > 3)
trigger2 = stateno = 200
;trigger2 = animelem = 4, >0
trigger2 = movecontact
trigger3 = stateno = 215
trigger3 = animelem = 4, >0
trigger3 = movecontact
trigger4 = stateno = 210
;trigger4 = animelem = 5, >0
trigger4 = movecontact
trigger5 = stateno = 235
;trigger5 = animelem = 3, <0
trigger5 = movecontact
trigger6 = stateno = 300
trigger6 = movecontact
trigger7 = stateno = 400
;trigger7 = animelem = 3, >0
trigger7 = movecontact

[State -1]
type = ChangeState
value = 1450
triggerall = !var(59)
triggerall = (command = "1450" && command != "1000")
triggerall = statetype != A
;triggerall = (stateno = 100 && time > 1)
trigger1 = ctrl
trigger2 = stateno = 200
;trigger2 = animelem = 4, >0
trigger2 = movecontact
trigger3 = stateno = 215
trigger3 = animelem = 4, >0
trigger3 = movecontact
trigger4 = stateno = 210
;trigger4 = animelem = 5, >0
trigger4 = movecontact
trigger5 = stateno = 235
;trigger5 = animelem = 3, <0
trigger5 = movecontact
trigger6 = stateno = 300
trigger6 = movecontact
trigger7 = stateno = 400
;trigger7 = animelem = 3, >0
trigger7 = movecontact




;------------------------
;å„ãŸã}âÒî
[State -1, T S]
type = ChangeState
value = 710
triggerall = !var(59)
triggerall = command = "recovery" && command = "holdback"
trigger1 = statetype != A
trigger1 = ctrl
;;;;;;;;trigger2 = power >= 1000
;;;;;;;;;trigger2 = stateno = [150,151]

[State -1, T S]
type = ChangeState
value = 710
triggerall = !var(59)
triggerall = command = "recovery" && command = "holdback"
triggerall = power >= 1000
trigger1 = stateno = 150
trigger2 = stateno = 151


;ëOãŸã}âÒî
[State -1, T S]
type = ChangeState
value = 700
triggerall = !var(59)
triggerall = command = "recovery"
trigger1 = statetype != A
trigger1 = ctrl
trigger2 = stateno = 100
;;;;;;;;;;;trigger2 = power >= 1000
;;;;;;;;;;;;trigger2 = stateno = [150,151]

[State -1, T S]
type = ChangeState
value = 700
triggerall = !var(59)
triggerall = command = "recovery"
triggerall = power >= 1000
trigger1 = stateno = 150
trigger2 = stateno = 151


[State -1, UKEMI]
type = ChangeState
value = 52000
triggerall = !var(59)
triggerall = command = "recovery"
triggerall = alive = 1
trigger1 = stateno = 5050
trigger1 = pos y > -30

;;;;;;;;;;;;;;;;;;;;;;;;;

[State -1]
type = ChangeState
value = 650
;triggerall = !var(59)
triggerall = command = "by"
triggerall = statetype = A
trigger1 = ctrl

[State -1, 290]
type = ChangeState
value = 260
;triggerall = !var(59)
triggerall = command = "by"
triggerall = power >= 1000
trigger1 = stateno = 150
trigger2 = stateno = 151

[State -1, Throw]
type = ChangeState
value = 250
triggerall = !var(59)
triggerall = command = "by"
triggerall = statetype != A
triggerall = stateno != 100
trigger1 = ctrl
;trigger2 = power >= 1000
;trigger2 = stateno = [150,151]

;É_ÉbÉVÉÖ
[State -1, Dash]
type = ChangeState
value = 100
;triggerall = !var(59)
triggerall = command = "FF"
trigger1 = statetype = S
trigger1 = ctrl
trigger1 = StateNo != 100

;ÉoÉbÉNÉXÉeÉbÉv
[State -1, Back Step]
type = ChangeState
value = 105
;triggerall = !var(59)
triggerall = command = "BB"
trigger1 = statetype = S
trigger1 = ctrl
trigger1 = StateNo != 100

[State -1]
type = ChangeState
value = 870
triggerall = !var(59)
triggerall = statetype = A
triggerall = ctrl
triggerall = p2bodydist X < 6
triggerall = p2bodydist Y = (-20,20)
trigger1 = command = "throw1" || command = "throw2" || command = "throw3"
trigger1 = command != "holdup"
trigger1 = stateno != 100 &&p2statetype = A
trigger1 = p2movetype != H

[State -1, Throw]
type = ChangeState
value = 800
;triggerall = !var(59)
triggerall = command = "y"
triggerall = p2movetype != H
triggerall = (p2statetype = S) || (p2statetype = C)
triggerall = statetype = S
triggerall = stateno != 100
triggerall = stateno != 102
triggerall = ctrl
trigger1 = (Command = "holdfwd" && P2Dist X < 40) || (Command = "holdback" && P2Dist X < 40)
trigger1 = command != "1500" || command != "1501"
trigger1 = ctrl

[State -1, Throw]
type = ChangeState
value = 860
;triggerall = !var(59)
triggerall = command = "b"
triggerall = p2movetype != H
triggerall = (p2statetype = S) || (p2statetype = C)
triggerall = statetype = S
triggerall = stateno != 100
triggerall = stateno != 102
triggerall = ctrl
trigger1 = (Command = "holdfwd" && P2Dist X < 46) || (Command = "holdback" && P2Dist X < 46)
trigger1 = command != "holdup"
trigger1 = ctrl

[State -1, AKZ]
type = ChangeState
value = 301
triggerall = !var(59)
triggerall = command = "a1"
triggerall = (command = "holdfwd" && command != "holddown" && command != "1000")
triggerall = statetype = S
trigger1 = ctrl
trigger2 = (stateno = 100 && time > 5)
;trigger3 = AnimElem = 3, >= 1 && AnimElem = 3, <= 4 && anim = 215
trigger3 = anim = 215
trigger3 = Animelem = 3,>= 1 && Animelem = 4,< 0
trigger3 = movecontact
trigger4 = anim = [200,205]
trigger4 = movecontact

[State -1, AKZ]
type = ChangeState
value = 300
triggerall = !var(59)
triggerall = command = "a1"
triggerall = (command = "holdfwd" && command != "holddown" && command != "1000")
triggerall = statetype = S
trigger1 = ctrl
trigger2 = (stateno = 100 && time > 5)


[State -1, Stand Light Punch]
type = ChangeState
value = 205
triggerall = !var(59)
triggerall = command = "x"
triggerall = command != "holddown"
triggerall = statetype = S
triggerall = p2bodydist X < 40;46
trigger1 = ctrl


[State -1, Stand Light Punch]
type = ChangeState
value = 200
triggerall = !var(59)
triggerall = command = "x"
triggerall = command != "holddown"
triggerall = statetype = S
trigger1 = ctrl

;ãﬂãóó£óßÇøã≠ÉpÉìÉ`
[State -1, Stand Strong Punch]
type = ChangeState
value = 215
triggerall = !var(59)
triggerall = command = "y"
triggerall = command != "holddown"
triggerall = statetype = S
triggerall = p2bodydist X < 40;46
trigger1 = ctrl
trigger2 = stateno = 400 && movecontact
trigger2 = Animelem = 2,>0 && Animelem = 2,<=7

;âìãóó£óßÇøã≠ÉpÉìÉ`
[State -1, Stand Strong Punch]
type = ChangeState
value = 210
triggerall = !var(59)
triggerall = command = "y"
triggerall = command != "holddown"
triggerall = statetype = S
trigger1 = ctrl

[State -1, Stand Light Kick]
type = ChangeState
value = 235
triggerall = !var(59)
triggerall = command = "a"
triggerall = command != "holddown"
triggerall = statetype = S
triggerall = P2bodydist X < 18
trigger1 = ctrl

;âìãóó£óßÇøé„ÉLÉbÉN
[State -1, Stand Light Kick]
type = ChangeState
value = 230
triggerall = !var(59)
triggerall = command = "a"
triggerall = command != "holddown"
triggerall = statetype = S
triggerall = P2bodydist X >= 18
trigger1 = ctrl


[State -1, Standing Strong Kick]
type = ChangeState
value = 245
triggerall = !var(59)
triggerall = command = "b"
triggerall = command != "holddown"
triggerall = statetype = S
triggerall = p2bodydist X < 20
trigger1 = ctrl

;âìãóó£óßÇøã≠ÉLÉbÉN
[State -1, Standing Strong Kick]
type = ChangeState
value = 240
triggerall = !var(59)
triggerall = command = "b"
triggerall = command != "holddown"
triggerall = statetype = S
trigger1 = ctrl

[State -1, Taunt]
type = ChangeState
value = 195
triggerall = !var(59)
triggerall = command = "start"
triggerall = statetype != A
trigger1 = ctrl


[State -1, Crouching Light Punch]
type = ChangeState
value = 400
triggerall = !var(59)
triggerall = command = "x"
triggerall = command = "holddown"
trigger1 = statetype = C
trigger1 = ctrl
trigger2 = stateno = 430 && time >= 7 && movecontact
;trigger3 = stateno = 400; && movecontact
;trigger3 = Animelem = 4,<0; && Animelem = 2,<=7


[State -1, Crouching Strong Punch]
type = ChangeState
value = 410
;triggerall = !var(59)
triggerall = command = "y"
triggerall = command = "holddown"
trigger1 = statetype = C
trigger1 = ctrl


[State -1, Crouching Light Kick]
type = ChangeState
value = 430
;triggerall = !var(59)
triggerall = command = "a"
triggerall = command = "holddown"
trigger1 = statetype = C
trigger1 = ctrl

[State -1, Crouching Strong Kick]
type = ChangeState
value = 440
triggerall = !var(59)
triggerall = command = "b"
triggerall = command = "holddown"
trigger1 = statetype = C
trigger1 = ctrl


[State -1, Jump Light Punch]
type = ChangeState
value = 600
triggerall = !var(59)
triggerall = command = "x"
trigger1 = statetype = A
trigger1 = stateno != 105
trigger1 = ctrl
;trigger2 = vel X != 0


;[State -1, Jump Light Punch]
;type = ChangeState
;value = 605
;triggerall = command = "x"
;trigger1 = statetype = A
;trigger1 = stateno != 105
;trigger1 = ctrl
;trigger2 = vel X = 0


[State -1, Jump Strong Punch]
type = ChangeState
value = 610
triggerall = !var(59)
triggerall = command = "y"
triggerall = stateno != 105
trigger1 = statetype = A
trigger1 = ctrl


[State -1, Jump Light Kick]
type = ChangeState
value = 630
triggerall = !var(59)
triggerall = command = "a"
triggerall = stateno != 105
trigger1 = statetype = A
trigger1 = ctrl

[State -1, Jump Light Kick]
type = ChangeState
value = 640
triggerall = !var(59)
triggerall = command = "b"
triggerall = stateno != 105
trigger1 = statetype = A
trigger1 = ctrl

;;;;;;;;;;;;;;;

[Statedef 104];AIópÉ_ÉbÉVÉÖ
type    = S
physics = N
anim = 100
ctrl = 0

[State 100]
type = VelSet
trigger1 = AnimElem = 2,>=0
x = const(velocity.run.fwd.x)-0.5

[State 100]
type = PlaySnd
trigger1 = AnimElem = 2
volume = -100
value = 100,0
channel = 4

[State 100,]
type = AssertSpecial
trigger1 = 1
flag = NoWalk

[State 100,]
type = AssertSpecial
trigger1 = 1
flag = NoAutoTurn

;[State 100, 8]
;type = ChangeState
;trigger1 = AnimElem = 2,>=0
;trigger1 = command = "holddown" || (command = "holdfwd" && command = "holddown")
;trigger1 = p2bodydist X = [3,40]
;value = 10
;ctrl = 1

[State 100, 8]
type = ChangeState
trigger1 = AnimElem = 2,>=0
trigger1 = p2bodydist X = [100,150]
trigger1 = random <= 500
value = 40
ctrl = 0

[State 100, 8]
type = ChangeState
trigger1 = AnimElem = 3,>=0
trigger1 = p2statetype = A || p2stateno = 5120 || (p2bodydist X = [10,35]) || (p2movetype = A && inguarddist)
trigger1 = random >= 500
;trigger2 = p2bodydist X <= 35 || p2movetype = A && inguarddist
;trigger3 = (Enemy, NumProj >= 1) || (Enemy, Numhelper >= 1)
;trigger3 = inguarddist
value = 102
ctrl = 1

;---------------------------------------------------------------------------



















